path: /blog/author/chris-lott
tag: Author
title: Chris Lott
subtitle: bio
pageName: Software Engineer
image: /images/lott_headshot.png
color: orange
buttons:
  - {}
actionBar:
  buttons:
    - color: purple
  enabled: true
meta:
  favicon: /images/mark_light_bg.png
  robots: 'index, follow'
  title: Chris Lott | Stoplight
  twitter:
    title: Chris Lott | Stoplight
    username: '@stoplightio'
pagination: {}
