path: /blog/author/matt-groberg
tag: author
title: Matt Groberg
subtitle: >-
  Matt Groberg is a web developer with a background in botany. He creates interactive 
  user interfaces for websites and apps using modern JavaScript frameworks.
pageName: Writer
image: /images/groberg-headshot.jpg
tabs:
  - {}
actionBar:
  ctas:
    - color: purple
  enabled: false
meta:
  favicon: /images/mark_light_bg.png
  title: Matt Groberg | Stoplight
  robots: 'index, follow'
  twitter:
    title: Matt Groberg | Stoplight
    username: '@stoplightio'
pagination: {}
