path: /blog/author/taylor-barnett
tag: author
title: Taylor Barnett
subtitle: >-
  Taylor Barnett is a community engineer and developer relations expert.  She's passionate about building great developer experiences with an
  emphasis on empathy and inclusion within APIs, documentation, support, and
  other community-focused projects. She has spoken at conferences such as
  O'Reilly OSCON, API Strategy & Practices, DevXcon, and various local meetups
  about APIs, developer experience, SDKs, and building developer communities.
pageName: Contributing Writer
image: /images/barnett_headshot.png
actionBar:
  enabled: false
meta:
  favicon: /images/mark_light_bg.png
  title: Taylor Barnett | Stoplight
  twitter:
    title: Taylor Barnett | Stoplight
    username: '@stoplightio'
pagination: {}
