[build]
  NODE_VERSION = "10"
  YARN_VERSION = "1.16.0"
  publish = "dist"
  command = "npm run build.production"

[context.deploy-preview]
  NODE_VERSION = "10"
  YARN_VERSION = "1.16.0"
  command = "npm run build"

[context.branch-deploy]
  NODE_VERSION = "10"
  YARN_VERSION = "1.16.0"
  command = "npm run build"