title: Documentation
slogan: Automatically generate customizable API documentation
description: >-
  Create a new or import an existing OpenAPI Specification document (formerly
  known as Swagger) and combine it with Markdown to create robust, internal and
  external API documentation for your organization. One-click cloud deployment
  with Stoplight or download the static assets to host anywhere.
callToAction: Some kind of clever call to action that drives people to this button.
signupText: >-
  The basic plan is **free**. 14 day trial for all features for **free**. No
  credit card required.
image: /images/product-page/docs-hero.png
featureList:
  - Interactive Documentation
  - Fully Customizable Pages
  - Versioning
  - Access Control
  - Integrations
features:
  - title: Layout & Theming
    description: >-
      Choose between a large or constrained layout and simply pick your colors
      and we will generate the rest. Use the CSS editor for further
      customization.
    image: /images/product-page/layout-and-theming.png
  - title: Add Some Basic Options
    description: >-
      Enhance your docs with a gif as a logo and enable mocked responses in the
      Try it out section.
    image: /images/product-page/add-some-basic-options.png
  - title: Put It All Together
    description: >-
      Easily protect your docs with a username and password. Turn on Segment,
      Intercom, or Google Analytics. Then Request user input variables such an
      API key to be used across your docs.
    image: /images/product-page/put-it-all-together.png
  - title: Preview and Publish
    description: >-
      View your docs before publishing. Then implement it either by hosting on
      our domain, your own custom domain, or embed to another website.
    image: /images/product-page/preview-and-publish.png
