title: Documentation
slogan: >-
  Automatically generate customizable API documentation. Because your API
  consumers deserve beautiful and interactive technical documentation.
description: >-
  Use OpenAPI Specification (formerly known as Swagger) and Markdown to create
  robust, internal and external API documentation for your organization.
  One-click cloud deployment with Stoplight or download the static assets to
  host anywhere.
callToAction: Some kind of clever call to action that drives people to this button.
signupText: >-
  The basic plan is **free**. 14 day trial for all features for **free**. No
  credit card required.
image: /images/product-page/docs-hero.png
featureList:
  - Interactive Documentation
  - Fully Customizable Pages
  - Versioning
  - Access Control
  - Integrations
features:
  - title: Interactive API Documentation
    description: >-
      You can no longer get by with static API documentation. That’s why
      Stoplight offers multiple ways for your API consumers to try out your API.
      Test Requests within your documentation allows consumers to understand how
      your API works. Code Examples generated from dozens of languages such as
      JavaScript, Python, Ruby, Java, cURL, and more allow consumers to copy and
      paste right into their own code. Built-in search directs consumers to the
      content they need.
    image: /images/product-page/layout-and-theming.png
  - title: 'Powerful, Visual Editor'
    description: >-
      With Themes, Custom CSS, Pages, and Domains, you control your
      documentation’s branding. With Custom Pages, you decide the page layout
      with our Markdown-based Editor. Giving you the freedom to add rich content
      and resources alongside your API reference documentation. Fully
      customizable site structure allows you to describe multiple APIs and
      resources in the same documentation with support for versioning. 
    image: /images/product-page/add-some-basic-options.png
  - title: Automated API Documentation
    description: >-
      Never have out-of-date documentation. Reference your OpenAPI Specification
      document to automatically generated API reference documentation. Use the
      Stoplight API to automate your documentation process by integrating it
      into your existing CI/CD workflow. 
    image: /images/product-page/put-it-all-together.png
  - title: 'Simple, Flexible Deployment'
    description: >-
      With flexible and secure deployment options, you can find a hosting
      solution that works for you. Allow Stoplight to host your documentation
      for you, so you never have to worry about managing servers for your
      documentation ever again. Manage access control and measure analytics with
      integrations. Or download the static assets or use our on-premise
      solutions behind your firewall to host your documentation from anywhere. 
    image: /images/product-page/preview-and-publish.png
