path: /about
color: blue-light
hero:
  title: Hi There
  subtitle: >-
    Stoplight is the best platform for an API design first approach. Easily create
    your design spec in any format. Then run tests, mock responses, and create
    beautiful documentation.
team:
  - name: Taylor Barnett
    role: Community Engineer
    image: /images/team/taylor-barnett.png
  - name: Nicholas Cassera
    role: Software Engineer
    image: /images/team/marc-macleod.png
  - name: Vincenzo Chianese
    role: Software Engineer
    image: /images/team/marc-macleod.png
  - name: Scott Faust
    role: Head of Growth
    image: /images/team/scott-faust.png
  - name: William Hilton
    role: Software Engineer
    image: /images/team/marc-macleod.png
  - name: Chris Lott
    role: Software Engineer
    image: /images/team/chris-lott.png
  - name: Marc MacLeod
    role: Founder & CEO
    twitter: '@marbemac'
    image: /images/team/marc-macleod.png
  - name: Ross Mcdonald
    role: Sales Engineer
    image: /images/team/ross-mcdonald.png
  - name: Vazha Omanashvili
    role: Software Engineer
    image: /images/team/vazha-omanashvili.png
  - name: Thomas Pytleski
    role: Software Engineer
    image: /images/team/thomas-pytleski.png
  - name: Brian Rock
    role: Director of Engineering
    image: /images/team/marc-macleod.png
  - name: Duane Tharp
    role: Sales & Partnerships
    image: /images/team/marc-macleod.png
  - name: Robert Wallach
    role: Content & Support
    image: /images/team/robert-wallach.png
actionBar:
  enabled: true
  text: Want to join the team? We're hiring!
  buttons:
    - text: Introduce Yourself
      link: mailto:hi@stoplight.io
      color: accent
quotes:
  - author: Mike Bissett
    company: BurstSMS
    image: /images/customers/burst-sms.png
    quote: >-
      Great product, really does take the pain out of creating and maintaining
      swagger specs.
    role: CTO
  - author: Mike Bissett
    company: BurstSMS
    image: /images/customers/burst-sms.png
    quote: >-
      Great product, really does take the pain out of creating and maintaining
      swagger specs.
    role: CTO
  - author: Mike Bissett
    company: BurstSMS
    image: /images/customers/burst-sms.png
    quote: >-
      Great product, really does take the pain out of creating and maintaining
      swagger specs.
    role: CTO
  - author: Mike Bissett
    company: BurstSMS
    image: /images/customers/burst-sms.png
    quote: >-
      Great product, really does take the pain out of creating and maintaining
      swagger specs.
    role: CTO
press:
  - description: Stoplight Launches Scenarios API Testing and Debugging Tool
    image: /images/press/programmableweb.png
    publication: Programmable Web
  - description: Stoplight Launches Scenarios API Testing and Debugging Tool
    image: /images/press/programmableweb.png
    publication: Programmable Web
investors:
  - name: NextGen Venture Partners
    image: /images/investors/nextgen-venture-partners.png
  - name: Capital Factory
    image: /images/investors/capital-factory.png
  - name: Techstars
    image: /images/investors/techstars.png
