path: /about
hero:
  subtitle: >-
    Headquartered in Austin, Texas, our team hails from all over the United
    States and Europe, united by their passion for APIs. From skeeball champions
    to rock climbers, tough mudders to restaurateurs, each and every member
    brings their own unique perspectives and experiences to the table. Thinking
    out of the box is our purpose, the weirder the better, and challenging the
    status quo is our culture
  title: About Us
team:
  - image: /public/images/barnett_headshot.png
    name: Taylor Barnett
    role: Community Engineer
  - image: /public/images/cassera_headshot.png
    name: Nicholas Cassera
    role: Software Engineer
  - image: /public/images/chianese_headshot.png
    name: Vincenzo Chianese
    role: Software Engineer
  - image: /public/images/faust_headshot.png
    name: Scott Faust
    role: Head of Growth
  - image: /public/images/hilton_headshot.png
    name: William Hilton
    role: Software Engineer
  - image: /public/images/lott_headshot.png
    name: Chris Lott
    role: Software Engineer
  - image: /public/images/macleod_headshot.png
    name: Marc MacLeod
    role: Founder & CEO
    twitter: '@marbemac'
  - image: /public/images/mcdonald_headshot.png
    name: Ross Mcdonald
    role: Sales Engineer
  - image: /images/team/vazha-omanashvili.png
    name: Vazha Omanashvili
    role: Software Engineer
  - image: /public/images/pytleski_headshot.png
    name: Thomas Pytleski
    role: Software Engineer
  - image: /public/images/rock_headshot.png
    name: Brian Rock
    role: Director of Engineering
  - image: /public/images/tharp_headshot.png
    name: Duane Tharp
    role: Sales & Partnerships
  - image: /public/images/wallach_headshot.png
    name: Robert Wallach
    role: Content & Support
quotes:
  - author: Evin Callahan
    company: Hudya
    image: /public/images/hudya_logo.png
    quote: >-
      Having all the tools to model, test, and document our API in one place,
      and integrating it nicely along the entire CI/CD workflow process has been
      extremely helpful for us.
    role: Cloud Architect
  - author: Josh Flyer
    company: AppointmentPlus
    image: /public/images/appointment_plus_logo.png
    quote: >-
      We really enjoy the modeling feature, helping us define our API before
      even writing code. Also, the way the modeling feature inherits models from
      other Projects. Hubs integrates with OAS files, both partials or the
      entire schema, which is rad.
    role: Lead Developer
  - author: Katie Corcos
    company: Namely
    image: /public/images/namely_logo.png
    quote: >-
      The UI was the best we had seen among all of the contenders thus far when
      it came to the user experience, design and customization.
    role: Technologist
  - author: Carlos Lozano
    company: GFT Group
    image: /public/images/gft_group_logo.jpg
    quote: >-
      Stoplight is getting better all the time. Big leap from [Stoplight]
      Classic.
    role: Senior Enterprise Architect
press:
  - description: Stoplight Launches Scenarios API Testing and Debugging Tool
    image: /images/press/programmableweb.png
    publication: Programmable Web
  - description: Stoplight Launches Scenarios API Testing and Debugging Tool
    image: /images/press/programmableweb.png
    publication: Programmable Web
investors:
  - image: /images/investors/nextgen-venture-partners.png
    name: NextGen Venture Partners
  - image: /images/investors/capital-factory.png
    name: Capital Factory
  - image: /images/investors/techstars.png
    name: Techstars
actionBar:
  buttons:
    - color: accent
      href: 'https://angel.co/stoplight/jobs'
      text: Learn More
  enabled: true
  text: Want to join the team? We're hiring!
