path: /blog
hero:
  subtitle: Musings on API design, testing, documentation, trends, and related technology.
  title: Stoplight API Corner
  bgColor: purple
actionBar:
  enabled: true
pagination:
  perPage: 2
  enabled: true
  basePath: '/blog'
meta:
  favicon: /images/mark_light_bg.png
  title: Stoplight API Corner | Stoplight
  twitter:
    title: Stoplight API Corner | Stoplight
    username: '@stoplightio'
