hero:
  particles: true
  bottomElem: true
  subtitle: >-
    Streamline your API Development workflow with a powerful API creation platform.
    Transform the way your team designs, documents, and mocks APIs.
  title: The Best APIs Start with Stoplight
  # image:
  #   alt: Documentation
  #   src: /images/placeholder.gif
  ctas:
    - color: purple
      href: https://stoplight.com/welcome
      large: true
      title: GET STARTED
pageSubjects:
  - title: API Design
    description: >-
      Know exactly what you need to build before writing a single line of code. Reduce your
      development time, minimize bugs, and improve your API’s longevity with Stoplight Studio.
    cta: Explore Studio
    href: /studio
    tag: design
    color: green
    icon: 'pencil-ruler'
    iconStyle:
      '--fa-primary-color': 'dodgerblue'
      '--fa-secondary-color': 'limegreen'
  - title: API Visibility
    description: >-
      Effectively navigate your APIs to visualize dependencies, increase
      reusability, and decrease redundancies with Stoplight Explorer.
    cta: Explore Visibility
    href: /studio
    tag: visibility
    color: blue
    icon: 'chart-network'
    iconStyle:
      '--fa-primary-color': 'tomato'
      '--fa-secondary-color': 'tomato'
  - title: API Documentation
    description: >-
      Automatically generate beautiful documentation and
      ensure it remains in sync with your API’s latest design specification.
    cta: Explore Docs
    href: /docs
    tag: documentation
    color: purple
    icon: 'book'
    iconStyle:
      '--fa-primary-color': 'gold'
      '--fa-secondary-color': 'gold'
  - title: Collaboration
    description: >-
      Collaborate with the entire team across one platform to implement specifications,
      merge microservices, and much more.
    cta: Explore Workspaces
    href: /docs
    tag: collaboration
    color: purple
    icon: 'user-friends'
    iconStyle:
      '--fa-primary-color': 'purple'
      '--fa-secondary-color': 'purple'
  # - title: Instant Hosted Mocking
  #   description: >-
  #     Integrate with an API before it's even built, enable teams to develop
  #     components in parallel, and break free from waterfall development.
  #   cta: Explore Mocking
  #   href: /mocking
  #   tag: mocking
  #   color: gold
  # - title: Create Quality Standards
  #   description: >-
  #     Accelerate development without sacrificing quality.
  #     Streamline every design decision with built-in linting and custom
  #     style guides.
  #   cta: Explore Quality
  #   href: /quality
  #   tag: quality
  #   color: indigo
solutions:
  - title: Solution One
    cta: Learn More
    href: /quality
    description: Here's some short text to describe
    tag: tag 1
    color: gold
  - title: Solution Two
    cta: Learn More
    href: /quality
    description: Here's some short text to describe
    tag: tag 2
    color: green
  - title: Solution Three
    cta: Learn More
    href: /quality
    description: Here's some short text to describe
    tag: tag 3
    color: indigo
  - title: Solution Four
    cta: Learn More
    href: /quality
    description: Here's some short text to describe
    tag: tag 4
    color: purple
features:
  - name: API Design
    description: Quickly model your APIs using visual tools on top of open standards.
    href: /design
    icon: 'pencil-ruler'
    iconStyle:
      '--fa-primary-color': 'dodgerblue'
      '--fa-secondary-color': 'limegreen'
  - name: API Documentation
    description: Increase customer adoption with beautiful, functional documentation.
    href: /documentation
    icon: 'book'
    iconStyle:
      '--fa-primary-color': 'tomato'
      '--fa-secondary-color': 'tomato'
  - name: API Mocking
    description: Easily mock web services and run scenarios from the command line.
    href: /mocking
    icon: 'server'
    iconStyle:
      '--fa-primary-color': 'slategray'
      '--fa-secondary-color': 'slategray'
caseStudies:
  - company: Arkea
    href: /case-studies/arkea
    image: /images/logo_arkea_transparent.png
    description: Arkéa has been involved in open banking for several years by providing white label banking services and saw PSD2 as an opportunity to extend their open banking features.
    tag: Finance
    color: orange
  - company: Namely
    href: /case-studies/namely
    image: /images/logo_namely_transparent.png
    description: Namely’s chief objective was to adopt API Design First principles. As they applied their new principle, they realized the importance of reliable, up to date, documentation.
    tag: HR
    color: indigo
  - company: Appointment Plus
    href: /case-studies/appointmentplus
    image: /images/logo_appointmentplus_transparent.png
    description: AppointmentPlus was managing multiple APIs built by different teams, at different times, with different strategies and intents.
    tag: Tech
    color: green
testimonials:
  actionBar:
    ctas:
      - color: white
        href: /demo
        outlined: true
        title: Book a Demo
      - color: purple
        href: /studio
        title: Get Started
    enabled: true
    text: Getting started is easy. Be up and running in minutes.
  testimonials:
    - author: Felix Sargent
      company: MediaMath
      image: /images/felix_s.jpg
      quote: >-
        Stoplight provides a clean user interface and enables an engineering
        team to develop a compliant API with minimal difficulty. Other tools
        don't provide the same details, guard rails, and error validation that
        Stoplight provides.
      role: Director of Engineering
    - author: Carlos Lozano
      company: GFT Group
      image: /images/carlos_testimonial.jpeg
      quote: >-
        When it comes to specification markup and documentation, the order of
        magnitude has gone from days to hours.
      role: Senior Enterprise Architect
    - author: John Vajda
      company: JumpCloud
      image: /images/testimonials/john_vajda.jpeg
      quote: >-
        Stoplight has been a serious game changer for JumpCloud’s API
        development! We love all the rich design, documentation and testing
        features, which has enabled us to design awesome APIs for our customers.
      role: Product Manager
    - author: Tim Slagle
      company: Zoom
      image: /images/testimonials/tim_s.jpg
      quote: >-
        Our team roughly saves 15-20 hours a week. It makes it quicker to write, and the review process is quicker as well because we can go in and everybody can see the edits.  We're pretty impressed with Stoplight as a whole.
      role: Manager of Developer Advocacy
meta:
  description: >-
    Using Stoplight you can create OpenAPI descriptions, documentation, mock
    servers much faster than other API tools, with no specialized knowledge
    required in one centralized platform.
  favicon: /images/mark_light_bg.png
  image: /images/studio/hero.png
  title: API Design Management for Teams and Enterprises | Stoplight
  twitter:
    description: >-
      Using Stoplight you can create OpenAPI descriptions, documentation, mock
      servers much faster than other API tools, with no specialized knowledge
      required in one centralized platform.
    image: /images/studio/hero.png
    title: API Design Management for Teams and Enterprises | Stoplight
