hero:
  bgColor: black
  cards:
    - bgColor: blue
      href: /design
      icon:
        name: paint-brush
        style: solid
      subtitle: Use our visual designer to manage OpenAPI (Swagger) 10x faster
      title: Design
    - bgColor: green
      href: /documentation
      icon:
        name: book
        style: solid
      subtitle: 'Increase customer adoption with beautiful, functional documentation'
      title: Documentation
    - bgColor: orange
      href: /testing
      icon:
        name: flask
        style: solid
      subtitle: 'Leverage OpenAPI to test, automate, and debug web APIs'
      title: Testing
    - bgColor: grey-darkest
      href: /mocking
      icon:
        name: server
        style: solid
      subtitle: 'Parallelize development with one click mock servers, powered by Prism'
      title: Mocking
  cta:
    href: 'https://next.stoplight.io/'
    name: Get Started Now
  particles: true
  skew: rounded
  subtitle: >-
    Stoplight leverages your OpenAPI documents to drive the entire API
    development process
  title: 'Best in class API Design, Docs, Mocking, and Testing'
collage:
  cta:
    color: green
    href: /case-studies
    name: Read the Case Studies
  images:
    - alt: EA
      src: /images/ea.png
    - alt: Arkea
      src: /images/logo_arkea_transparent.png
    - alt: Chargify
      src: /images/chargify-new-logo.png
    - alt: Deutsche Bank
      src: /images/deutsche_bank.png
    - alt: quicken
      src: /images/customers/quicken.png
    - alt: Sendgrid
      src: /images/logo-sendgrid.png
    - alt: Shopgate
      src: /images/shopgate.png
    - alt: Spotify
      src: /images/spotify.png
    - alt: TiVo
      src: /images/tivo.png
    - alt: Zendesk
      src: /images/logo_zendesk.png
meta:
  favicon: /images/mark_light_bg.png
  title: The Complete API Toolkit for Teams and Enterprises | Stoplight
  twitter:
    image: /images/mark_light_bg.png
    title: The Complete API Toolkit for Teams and Enterprises | Stoplight
    username: '@stoplightio'
