hero:
  particles: true
  bottomElem: false
  skew: false
  subtitle: >-
    Supercharge your API lifecycle with best-in-class tooling that integrates seamlessly into your workflows
  title: Build Quality APIs Faster

  # image:
  #   alt: Documentation
  #   src: /images/placeholder.gif
  ctas:
    - color: blue2
      href: https://stoplight.com/welcome
      large: true
      title: Get Started For Free
features:
  - title: Design
    subtitle: Design APIs in Minutes
    description: >-
      Empower technical and non-technical stakeholders to create and collaborate 
      on API designs in OpenAPI and JSON Schema using an intuitive user interface.
    image: /images/home/design.svg
    cta: Learn More
    titleURL: /solutions/design
  - title: Documentation
    subtitle: Build Beautiful Developer Experiences
    description: >-
      Drive API adoption by providing internal and external 
      developers with always up-to-date interactive documentation, tutorials, and code samples.
    image: /images/home/developer_experience.svg
    cta: Learn More
    titleURL: /solutions/documentation
  - title: Visibility
    subtitle: Maintain a Central Source of Truth
    description: >-
      Promote reuse, consistency, and quality by navigating API design artifacts across your organization 
      in an easily searchable and manageable technical knowledge base.
    image: /images/home/visibility.svg
    cta: Learn More
    titleURL: /solutions/visibility
  - title: Governance
    subtitle: Adhere to Best Practices
    description: >-
      Design consistent APIs by automatically validating against predefined 
      or custom style guidelines within the API designer.
    image: /images/home/governance.svg
    cta: Learn More
    titleURL: /solutions/governance
  - title: Mocking
    subtitle: Increase Developer Productivity
    description: >-
      Get early feedback on API designs to avoid changes and enable API consumers and producers 
      to build in parallel with instant mock servers.
    image: /images/home/mock.svg
    cta: Learn More
    titleURL: /solutions/mocking
  - title: Collaboration
    subtitle: Promote Stakeholder Alignment
    description: >-
      Streamline your workflow by encouraging all stakeholders - 
      from business to engineering - internal or external, to collaborate 
      across the API design and development lifecycle.
    image: /images/home/collaboration.svg
    cta: Learn More
    titleURL: /solutions/collaboration
vcs:
  title: All this while integrating seamlessly with your favorite VCS
  description: >-
    Connect easily with Git providers to always stay on top of project changes. No awkward two-way sync, 
    work directly with repositories fitting comfortably into existing Git workflows.
  cta: Learn More
  href: /design
  images:
    - img: /images/integrations/gitlab.svg
    - img: /images/integrations/github.svg
    - img: /images/integrations/bitbucket.svg
    - img: /images/integrations/gitea.svg
collage:
  images:
    - alt: EA
      src: /images/ea.png
#    - alt: Arkea
#      src: /images/logo_arkea_transparent.png
    - alt: Chargify
      src: /images/chargify-new-logo.png
#    - alt: Deutsche Bank
#      src: /images/deutsche_bank.png
    - alt: Sendgrid
      src: /images/logo-sendgrid.png
#    - alt: Shopgate
#      src: /images/shopgate.png
    - alt: TiVo
      src: /images/tivo.png
    - alt: Zoom
      src: /images/zoom_logo.png
#    - alt: EA
#      src: /images/ea.png
#    - alt: Arkea
#      src: /images/logo_arkea_transparent.png
  title: >-
# pageSubjects:
# - title: Source of Truth
#   description: >-
#     Promote reuse, consistency, and quality by sharing API design artifacts across your organization in an easily searchable and manageable design library.
#   cta: Explore Visibility Solutions
#   href: /solutions/visibility/
#   tag: visibility
#   color: green
#   icon: 'chart-network'
#   iconStyle:
#     '--fa-primary-color': 'limegreen'
#     '--fa-secondary-color': 'limegreen'
# - title: Design APIs Quickly
#   description: >-
#     Empower technical and non-technical stakeholders to create and collaborate on API designs in OpenAPI and JSON Schema using an intuitive user interface
#   cta: Explore Design Solutions
#   href: /solutions/design/
#   tag: design
#   color: blue
#   icon: 'pencil-ruler'
#   iconStyle:
#     '--fa-primary-color': 'dodgerblue'
#     '--fa-secondary-color': 'limegreen'
# - title: Developer Docs
#   description: >-
#     Drive API adoption by helping internal and external developers consume APIs easily using interactive documentation with code samples.
#   cta: Explore Explorer
#   href: /explorer
#   tag: visibility
#   color: purple
#   icon: 'book'
#   iconStyle:
#     '--fa-primary-color': 'tomato'
#     '--fa-secondary-color': 'tomato'
# - title: Hosted Mocking
#   description: >-
#     Develop alongside a hosted mock server to enable frontend and backend teams to develop in parallel.
#   cta: Explore Mocking
#   href: /mocking
#   tag: validation
#   color: gold
#   icon: 'server'
#   iconStyle:
#     '--fa-primary-color': 'indigo'
#     '--fa-secondary-color': 'indigo'
# solutions:
#   - title: Provide an Amazing Developer Experience
#     cta: Learn More About API Documentation
#     description: >-
#       Drive API adoption by helping internal and external developers consume APIs easily using interactive documentation with code samples.
#     tag: documentation
#     color: green
#     icon: 'user-friends'
#     iconStyle:
#       '--fa-primary-color': 'limegreen'
#       '--fa-secondary-color': 'green'
#   - title: One Shared Source of Truth
#     cta: Learn More About API Visibility
#     href: /solutions/visibility/
#     description: >-
#       Promote reuse, consistency, and quality by sharing API design artifacts across your organization in an easily searchable and manageable design library.
#     tag: visibility
#     color: orange
#     icon: 'code-branch'
#     iconStyle:
#       '--fa-primary-color': 'tomato'
#       '--fa-secondary-color': 'tomato'
#   - title: Design Beautiful APIs Quickly
#     cta: Learn More About API Design
#     href: /solutions/design/
#     description: >-
#       Empower technical and non-technical stakeholders to create and collaborate on API designs in OpenAPI and JSON Schema using an intuitive user interface.
#     tag: design
#     color: indigo
#     icon: 'code'
#     iconStyle:
#       '--fa-primary-color': 'indigo'
#       '--fa-secondary-color': 'indigo'
#   - title: Adhere to Best Practices
#     cta: Learn More About API Governance
#     href: /solutions/governance
#     description: >-
#       Design consistent APIs by automatically validating against predefined or custom style guidelines within the API designer.
#     tag: Governance
#     color: purple
#     icon: 'badge-check'
#     iconStyle:
#       '--fa-primary-color': 'dodgerblue'
#       '--fa-secondary-color': 'dodgerblue'
# features:
#   - name: API Design
#     description: Quickly model your APIs using visual tools on top of open standards.
#     href: /design
#     icon: 'pencil-ruler'
#     iconStyle:
#       '--fa-primary-color': 'dodgerblue'
#       '--fa-secondary-color': 'limegreen'
#   - name: API Documentation
#     description: Increase customer adoption with beautiful, functional documentation.
#     href: /documentation
#     icon: 'book'
#     iconStyle:
#       '--fa-primary-color': 'tomato'
#       '--fa-secondary-color': 'tomato'
#   - name: API Mocking
#     description: Easily mock web services and run scenarios from the command line.
#     href: /mocking
#     icon: 'server'
#     iconStyle:
#       '--fa-primary-color': 'slategray'
#       '--fa-secondary-color': 'slategray'
# caseStudies:
#   - company: Arkea
#     href: /case-studies/arkea
#     image: /images/logo_arkea_transparent.png
#     description: Arkéa has been involved in open banking for several years by providing white label banking services and saw PSD2 as an opportunity to extend their open banking features.
#     tag: Finance
#     color: orange
#   - company: Namely
#     href: /case-studies/namely
#     image: /images/logo_namely_transparent.png
#     description: Namely’s chief objective was to adopt API Design First principles. As they applied their new principle, they realized the importance of reliable, up to date, documentation.
#     tag: HR
#     color: indigo
#   - company: Appointment Plus
#     href: /case-studies/appointmentplus
#     image: /images/logo_appointmentplus_transparent.png
#     description: AppointmentPlus was managing multiple APIs built by different teams, at different times, with different strategies and intents.
#     tag: Tech
#     color: green
testimonials:
  # actionBar:
  #   ctas:
  #     - color: white
  #       href: /demo
  #       outlined: true
  #       title: Book a Demo
  #     - color: purple
  #       href: /studio
  #       title: Get Started
  #   enabled: false
  #   text: Getting started is easy. Be up and running in minutes.
  testimonials:
    - author: Felix Sargent
      company: MediaMath
      image: /images/felix_s.jpg
      quote: >-
        Stoplight enables our engineering team to develop compliant APIs with minimal difficulty.
      role: Director of Engineering
    - author: Nicolas Tisserand
      company: Arkéa
      image: /images/customers/nicolas-t.jpeg
      quote: >-
        Thanks to Stoplight's visual API editor our Product Owners are now a critical part of the API design process. 
      role: API Management Architect
    # - author: John Vajda
    #   company: JumpCloud
    #   image: /images/testimonials/john_vajda.jpeg
    #   quote: >-
    #     Stoplight has been a serious game changer for JumpCloud’s API
    #     development! We love all the rich design, documentation and testing
    #     features, which has enabled us to design awesome APIs for our customers.
    #   role: Product Manager
    # - author: Tim Slagle
    #   company: Zoom
    #   image: /images/testimonials/tim_s.jpg
    #   quote: >-
    #     Our team roughly saves 15-20 hours a week. It makes it quicker to write, and the
    #     review process is quicker as well because we can go in and everybody can see the edits.
    #     We're pretty impressed with Stoplight as a whole.
    #   role: Manager of Developer Advocacy
actionBar:
  ctas:
    - color: blue2
      href: '/welcome'
      title: Get Started For Free
  enabled: true
  text: Ready to get started building better APIs?
meta:
  description: >-
    Using Stoplight you can create OpenAPI descriptions, documentation, mock
    servers much faster than other API tools, with no specialized knowledge
    required in one centralized platform.
  favicon: /images/mark_light_bg.png
  image: /images/studio/hero.png
  title: API Design Management | Designing APIs For Teams and Enterprise | Stoplight
  twitter:
    description: >-
      Using Stoplight you can create OpenAPI descriptions, documentation, mock
      servers much faster than other API tools, with no specialized knowledge
      required in one centralized platform.
    image: /images/studio/hero.png
    title: API Design Management | Designing APIs For Teams and Enterprise | Stoplight
