hero:
  title: Best in class API Design, Docs, Mocking, and Testing
  subtitle: Stoplight leverages your OpenAPI files to drive the entire API development process.
  cta:
    name: Get Started Now
  bgColor: black
  particles: true
  bowl: true
  cards:
    - title: API Designer
      subtitle: Use our visual designer to manage OpenAPI (Swagger) 10x faster.
      href: /api-design
      bgColor: blue
      icon:
        style: solid
        name: paint-brush
    - title: Technical Docs
      subtitle: Increase customer adoption with beautiful, functional documentation.
      href: /api-documentation
      bgColor: green
      icon:
        style: solid
        name: book
    - title: Contract Testing
      subtitle: Leverage OpenAPI to test, automate, and debug web APIs.
      href: /api-testing
      bgColor: orange
      icon:
        style: solid
        name: flask
    - title: API Mocking
      subtitle: Parallelize development with one click mock servers, powered by OpenAPI.
      href: /api-mocking
      bgColor: grey-darkest
      icon:
        style: solid
        name: server
product:
  title: The Complete OpenAPI (Swagger) Toolkit
  image: /images/home-hero.png
  cta:
    name: Get Started Now
  description: >-
    Create OpenAPI documents 10x faster with no specialized knowledge required.
    Combine OpenAPI files with markdown to create beautiful documentation for internal and external
    stakeholders. Instantly turn any OpenAPI file into a mock server. Leverage contract testing to ensure that
    your single source of truth - OpenAPI - accurately describe your APIs.
customers:
  - '/images/customers/ea.png'
  - '/images/customers/arkea.png'
  - '/images/customers/chargify.png'
  - '/images/customers/deutsche-bank.png'
  - '/images/customers/quicken.png'
  - '/images/customers/sendgrid.png'
  - '/images/customers/shopgate.png'
  - '/images/customers/spotify.png'
  - '/images/customers/tivo.png'
  - '/images/customers/zendesk.png'
testimonials:
  - image: /images/testimonials/kin_lane.jpeg
    quote: I feel like Stoplight has the potential to shift the landscape pretty significantly, something I haven't seen any API service provider do in a while.
    author: Kin Lane
    role: API Evangelist
  - image: /images/testimonials/bruce_wang.jpeg
    quote: Stoplight allows for better public API docs and internal microservice API discovery/management.
    author: Bruce Wang
    role: CTO, Synq.fm
  - image: /images/testimonials/john_vajda.jpeg
    quote: Stoplight has been a serious game changer for JumpCloud’s API development! We love all the rich design, documentation and testing features, which has enabled us to design awesome APIs for our customers.
    author: John Vajda
    role: Product Manager, JumpCloud
  - image: /images/testimonials/gil.jpeg
    quote: Stoplight provides a centralized, testable and reliable source for our APIs.
    author: Gil Barbara
    role: Frontend Engineer, AMARO
actionBar:
  enabled: true
  text: Getting started is easy.
  buttons:
    - text: Sign Up
      link: https://next.stoplight.io/join
      color: accent
