hero:
  particles: true
  bottomElem: true
  subtitle: >-
    Streamline your API Development workflow with a powerful API creation platform.
    Transform the way your team designs, documents, and mocks APIs.
  title: The Best APIs Start with Stoplight
  # image:
  #   alt: Documentation
  #   src: /images/placeholder.gif
  ctas:
    - color: purple
      href: https://stoplight.com/welcome
      large: true
      title: GET STARTED
pageSubjects:
  - title: Design APIs
    description: >-
      Quickly create, collaborate, and prototype OpenAPI design specifications for your next API.
    cta: Explore Studio
    href: /studio
    tag: design
    color: green
    icon: 'pencil-ruler'
    iconStyle:
      '--fa-primary-color': 'dodgerblue'
      '--fa-secondary-color': 'limegreen'
  - title: Doc Generation
    description: >-
      Automatically generate beautiful and interactive documentation that is always in-sync with your API's design specification.
    cta: Explore Docs
    href: /docs
    tag: docs
    color: blue
    icon: 'book'
    iconStyle:
      '--fa-primary-color': 'tomato'
      '--fa-secondary-color': 'tomato'
  - title: APIs at Scale
    description: >-
      Effectively navigate your APIs in an instant with Stoplight's technical knowledge base.
    cta: Explore Explorer
    href: /docs
    tag: visibility
    color: purple
    icon: 'chart-network'
    iconStyle:
      '--fa-primary-color': 'limegreen'
      '--fa-secondary-color': 'limegreen'
  - title: Hosted Mocking
    description: >-
      Develop with a hosted mock server that automatically reconfigures to match your API's design specification.
    cta: Explore Mocking
    href: /docs
    tag: validation
    color: gold
    icon: 'server'
    iconStyle:
      '--fa-primary-color': 'indigo'
      '--fa-secondary-color': 'indigo'
solutions:
  - title: Maintain Stakeholder Alignment
    cta: Learn More About API Design
    href: /solutions/design
    description: >-
      Optimize how you and your team communicate & collaborate by utilizing API design. Create
      detailed requirements that ensure stakeholders are always coordinated.
    tag: design
    color: green
    icon: 'user-friends'
    iconStyle:
      '--fa-primary-color': 'limegreen'
      '--fa-secondary-color': 'green'
  - title: Optimize Your Development Workflow
    cta: Learn More About API Development
    href: /solutions/development
    description: >-
      API design first enables you to empower your architects and lead your developers. Streamline your development workflow
      to shorten time to market.
    tag: tag 2
    color: orange
    icon: 'code-branch'
    iconStyle:
      '--fa-primary-color': 'tomato'
      '--fa-secondary-color': 'tomato'
  - title: Reduce Integration Time
    cta: API Documentation
    href: /solutions/documentation
    description: >-
      Enable API consumers to integrate more efficiently with your API. Reallocate time spent by support staff guiding
      integrations with more complete and detailed API documentation.
    tag: tag 3
    color: indigo
    icon: 'code'
    iconStyle:
      '--fa-primary-color': 'dodgerblue'
      '--fa-secondary-color': 'dodgerblue'
  - title: Maintain Consistency & Quality
    cta: API Quality & Governance
    href: /solutions/governance
    description: >-
      Effectively maintain quality standards across all your APIs with Spectral. Integrated into Studio, never
      worry about manually enforcing style guides again.
    tag: tag 4
    color: purple
    icon: 'server'
    iconStyle:
      '--fa-primary-color': 'indigo'
      '--fa-secondary-color': 'indigo'
features:
  - name: API Design
    description: Quickly model your APIs using visual tools on top of open standards.
    href: /design
    icon: 'pencil-ruler'
    iconStyle:
      '--fa-primary-color': 'dodgerblue'
      '--fa-secondary-color': 'limegreen'
  - name: API Documentation
    description: Increase customer adoption with beautiful, functional documentation.
    href: /documentation
    icon: 'book'
    iconStyle:
      '--fa-primary-color': 'tomato'
      '--fa-secondary-color': 'tomato'
  - name: API Mocking
    description: Easily mock web services and run scenarios from the command line.
    href: /mocking
    icon: 'server'
    iconStyle:
      '--fa-primary-color': 'slategray'
      '--fa-secondary-color': 'slategray'
caseStudies:
  - company: Arkea
    href: /case-studies/arkea
    image: /images/logo_arkea_transparent.png
    description: Arkéa has been involved in open banking for several years by providing white label banking services and saw PSD2 as an opportunity to extend their open banking features.
    tag: Finance
    color: orange
  - company: Namely
    href: /case-studies/namely
    image: /images/logo_namely_transparent.png
    description: Namely’s chief objective was to adopt API Design First principles. As they applied their new principle, they realized the importance of reliable, up to date, documentation.
    tag: HR
    color: indigo
  - company: Appointment Plus
    href: /case-studies/appointmentplus
    image: /images/logo_appointmentplus_transparent.png
    description: AppointmentPlus was managing multiple APIs built by different teams, at different times, with different strategies and intents.
    tag: Tech
    color: green
testimonials:
  actionBar:
    ctas:
      - color: white
        href: /demo
        outlined: true
        title: Book a Demo
      - color: purple
        href: /studio
        title: Get Started
    enabled: true
    text: Getting started is easy. Be up and running in minutes.
  testimonials:
    - author: Felix Sargent
      company: MediaMath
      image: /images/felix_s.jpg
      quote: >-
        Stoplight provides a clean user interface and enables an engineering
        team to develop a compliant API with minimal difficulty. Other tools
        don't provide the same details, guard rails, and error validation that
        Stoplight provides.
      role: Director of Engineering
    - author: Carlos Lozano
      company: GFT Group
      image: /images/carlos_testimonial.jpeg
      quote: >-
        When it comes to specification markup and documentation, the order of
        magnitude has gone from days to hours.
      role: Senior Enterprise Architect
    - author: John Vajda
      company: JumpCloud
      image: /images/testimonials/john_vajda.jpeg
      quote: >-
        Stoplight has been a serious game changer for JumpCloud’s API
        development! We love all the rich design, documentation and testing
        features, which has enabled us to design awesome APIs for our customers.
      role: Product Manager
    - author: Tim Slagle
      company: Zoom
      image: /images/testimonials/tim_s.jpg
      quote: >-
        Our team roughly saves 15-20 hours a week. It makes it quicker to write, and the review process is quicker as well because we can go in and everybody can see the edits.  We're pretty impressed with Stoplight as a whole.
      role: Manager of Developer Advocacy
actionBar:
  ctas:
    - color: accent
      href: '/careers'
      title: Learn More
  enabled: true
  text: Ready to get started building better APIs?
meta:
  description: >-
    Using Stoplight you can create OpenAPI descriptions, documentation, mock
    servers much faster than other API tools, with no specialized knowledge
    required in one centralized platform.
  favicon: /images/mark_light_bg.png
  image: /images/studio/hero.png
  title: API Design Management for Teams and Enterprises | Stoplight
  twitter:
    description: >-
      Using Stoplight you can create OpenAPI descriptions, documentation, mock
      servers much faster than other API tools, with no specialized knowledge
      required in one centralized platform.
    image: /images/studio/hero.png
    title: API Design Management for Teams and Enterprises | Stoplight
