path: /pricing
hero:
  particles: true
  title: Pricing
plans:
  - title: Free
    titleColor: green
    description: 'placeholder subtitle text if we want it'
    button:
      color: green
      title: Get Started
      href: 'https://stoplight.io/p/studio?utm_source=studio_landing&utm_medium=start_button&utm_campaign=dynamic_start'
    price:
      title: $0
    features:
      - name: Up to 10 users
      - name: Up to 5 projects
      - name: Native Git Sync
      - name: Private & Public Project Access
      - name: OAS3 Visual Designer
      - name: Hosted Mocking
      - name: JSON/YAML Linter
  - title: Team
    titleColor: indigo
    description: 'placeholder subtitle text if we want it'
    button:
      color: indigo
      title: Get Started
      href: 'https://stoplight.io/p/studio?utm_source=studio_landing&utm_medium=start_button&utm_campaign=dynamic_start'
    price:
      title: $19
    features:
      - name: Unlimited users
      - name: Up to 20 projects
      - name: Team Style Guides
      - name: Custom Domains
      - name: Theming
      - name: Custom Branding
      - name: Another thing
      - name: One more thing
  - title: Enterprise
    titleColor: purple
    description: 'placeholder subtitle text if we want it'
    button:
      color: purple
      title: Contact Us
      href: '/demo/'
    price:
      title: Custom Pricing
      button:
        color: purple
        title: Contact Us
        href: '/demo/'
    features:
      - name: Unlimited Projects
      - name: White Label Docs
      - name: Organizational Design Library
      - name: Design Library Model Masking
      - name: In & Outbound Dependency Graph
      - name: On-Premise Support
      - name: SSO & Authentication
      - name: Enterprise Terms & Support
collage:
  images:
    - alt: EA
      src: /images/ea.png
    - alt: Arkea
      src: /images/logo_arkea_transparent.png
    - alt: Chargify
      src: /images/chargify-new-logo.png
    - alt: Deutsche Bank
      src: /images/deutsche_bank.png
    - alt: Sendgrid
      src: /images/logo-sendgrid.png
    - alt: Shopgate
      src: /images/shopgate.png
    - alt: Spotify
      src: /images/spotify.png
    - alt: TiVo
      src: /images/tivo.png
    - alt: Zendesk
      src: /images/logo_zendesk.png
  title: >-
    Thousands of companies use Stoplight to streamline their API & Microservices
    workflow
faq:
  title: Frequently Asked Questions
  description: Don't see your question? [Talk to a solutions engineer](https://stoplight.io/demo).

  questions:
    - question: How is usage calculated?
      answer: >-
        In Stoplight, APIs are organized into workspaces. Each workspace is associated with a user account's billing profile.
        Your usage is the sum of the users and resources across all of the workspaces connected to your billing profile.
    - question: What happens if I go over my limits?
      answer: >-
        Nothing will be disabled or changed immediately. You will receive an email asking you to updating your billing, or lower your usage.
        If, after 7 days, you have not updated your billing, the associated workspaces will be disabled until your account is back in good standing.
    - question: How many APIs can I publish with the Standard and PRO plans?
      answer: >-
        No limits! As long as you are within your 2,500 free resources, you can publish as many APIs as you like. We do not charge for anything on a per api basis - see the FAQ below for our rationale.
    - question: What is counted as a user?
      answer: >-
        Anyone invited to your workspaces in the Stoplight app is considered a user of that workspace. Only unique users are counted 
        towards your billing profile. If you invite the same user to multiple workspaces, it still counts as one user. 
        Users with the guest role are counted and applied to your limits.
    - question: Can I transfer a workspace to another billing account?
      answer: >-
        Absolutely, just head over to the billing section of the workspace in question, and then scroll down to the transfer section.
    - question: Is my credit card information secure?
      answer: >-
        Yes. All credit card processing is handled through Stripe, and your card information is never sent to, or stored on, our servers.
    - question: What is a "Resource"?
      answer: >-
        All the different parts that make up your API design and tests are considered resources.
    - question: I'm working on an open source, education, or non-profit project. Is there a discount?
      answer: >-
        Let's chat! Please send an email to customer@stoplight.io.
    - question: Why not measure usage on a per API basis?
      answer: >-
        Many other tools price on a per API basis, instead of per resource. 
        We believe that a resource based model is more flexible and fair, particularly as the industry moves towards 
        smaller and smaller services (microservices). One 1000 endpoint API should be priced the same as one hundred 10 endpoint APIs
    - question: Is there a free trial?
      answer: >-
        Yes. Every new account gets 14 days to try all of our tools, without limits.

actionBar:
  ctas:
    - color: accent
      href: '/demo'
      title: Book a Demo
  enabled: true
  text: Need help picking a plan? Speak with a Solutions Architect.
docPlans:
  title: Feature Breakdown by Plan
  features:
    - title: Design
      bold: true
    - title: Unlimited APIs, Models, Endpoints, Articles, & Images
      toolTip: Here's more information about this feature in a tool tip
      plans:
        - Free
        - Team
        - Enterprise
    - title: OpenAPI 3 form support
      toolTip: Here's more information about the OpenAPI 3 form support in a tool tip
      plans:
        - Free
        - Team
        - Enterprise
    - title: Native git integration
      toolTip: Here's more information about this feature in a tool tip
      plans:
        - Free
        - Team
        - Enterprise
    - title: Create and switch between branches
      toolTip: Here's more information about this feature in a tool tip
      plans:
        - Free
        - Team
        - Enterprise
    - title: Create projects from an existing directory/folder on your computer
      toolTip: Here's more information about this feature in a tool tip
      plans:
        - Free
        - Team
        - Enterprise
    - title: Powerful search
      plans:
        - Free
        - Team
        - Enterprise
    - title: Dark theme
      toolTip: Here's more information about this feature in a tool tip
      plans:
        - Free
        - Team
        - Enterprise
    - title: Private share links
      toolTip: Here's more information about this feature in a tool tip
      plans:
        - Free
        - Team
        - Enterprise
    - title: Style guides
      plans:
        - Team
        - Enterprise
    - title: Design library
      plans:
        - Enterprise
    - title: Design library model masking
      plans:
        - Enterprise
    - title: Design, Visbility & Governance
      bold: true
    - title: Git repo analysis & Auto discovery
      plans:
        - Free
        - Team
        - Enterprise
    - title: Data filters
      plans:
        - Free
        - Team
        - Enterprise
    - title: Project search
      plans:
        - Free
        - Team
        - Enterprise
    - title: Workspace search
      plans:
        - Free
        - Team
        - Enterprise
    - title: OpenAPI linter
      plans:
        - Free
        - Team
        - Enterprise
    - title: Dependency graph - inbound & outbound relationships
      plans:
        - Enterprise
    - title: Docs
      bold: true
    - title: Unlimited published APIs
      plans:
        - Free
        - Team
        - Enterprise
    - title: Integrated 'Try it out' API console
      plans:
        - Free
        - Team
        - Enterprise
    - title: Rich, markdown powered docs
      plans:
        - Free
        - Team
        - Enterprise
    - title: Export support
      plans:
        - Free
        - Team
        - Enterprise
    - title: Versioning support
      plans:
        - Free
        - Team
        - Enterprise
    - title: Complex JSON support
      plans:
        - Free
        - Team
        - Enterprise
    - title: Unlimited pageviews
      plans:
        - Free
        - Team
        - Enterprise
    - title: Build history and instant rollbacks
      plans:
        - Free
        - Team
        - Enterprise
    - title: Custom domains
      plans:
        - Team
        - Enterprise
    - title: Theming
      plans:
        - Team
        - Enterprise
    - title: Custom branding
      plans:
        - Team
        - Enterprise
    - title: White labeled
      plans:
        - Enterprise
    - title: Guest access
      plans:
        - Enterprise
    - title: Mocking
      bold: true
    - title: Hosted mocking
      plans:
        - Free
        - Team
        - Enterprise
    - title: Integrated mocking support within API console
      plans:
        - Free
        - Team
        - Enterprise
    - title: Validate inputs, responses, webhooks & callbacks
      plans:
        - Free
        - Team
        - Enterprise
    - title: Automatic reload
      plans:
        - Free
        - Team
        - Enterprise
    - title: Support
      bold: true
    - title: Dedicated customer success manager
      plans:
        - Enterprise
    - title: Invoicing options
      plans:
        - Enterprise
    - title: Bulk/scalable pricing
      plans:
        - Enterprise
    - title: Admin
      bold: true
    - title: SAML
      plans:
        - Enterprise
    - title: LDAP
      plans:
        - Enterprise
    - title: Domain capture
      plans:
        - Enterprise
    - title: On Premise
      plans:
        - Enterprise
  plans:
    - title: Free
    - title: Team
    - title: Enterprise
