path: /pricing
hero:
  title: Plans That Suit Your API Program
plans:
  - title: Free
    titleColor: blue2
    summary: 'Design and documentation basics to get started'
    addInfo:
    price:
      title: $0
    features:
      - name: Up to 10 Users
      - name: Up to 5 Projects
      - name: API Design with Stoplight Studio
      - name: Instant Mock Servers
      - name: API Style Guides
      - name: Interactive Docs
      - name: Custom Domains
    ctas:
      - color: blue2
        href: https://stoplight.io/welcome/create
        large: true
        title: Get Started
  - title: Starter
    titleColor: green
    summary: 'Collaborative design and customized docs for teams'
    addInfo: $8 / additional user
    price:
      title: $99
    features:
      - name: Everything in Free
      - name: 5 Users Included
      - name: Up to 50 Projects
      - name: Theming
      - name: Multi-Branch Support
      - name: Up to 1000 Changelogs
      - name: Approved Email Domains
    ctas:
      - color: green
        href: https://stoplight.io/welcome/create
        large: true
        title: Get Started
  - title: Professional
    titleColor: lavender
    summary: 'Governance, visibility, and reuse to deliver consistency and quality'
    addInfo: $24 / additional user
    price:
      title: $399
    features:
      - name: Everything in Starter
      - name: 10 Users Included
      - name: Unlimited Projects
      - name: Unlimited Changelogs
      - name: Guest Access
      - name: Remove Stoplight Branding
      - name: Dependency Tracking
      - name: Self Hosted Git Providers
      - name: LDAP & SAML SSO
    ctas:
      - color: lavender
        href: https://stoplight.io/welcome/create
        large: true
        title: Get Started
  - title: Enterprise
    titleColor: orange
    summary: 'Scale with best-in-class support and flexible deployment for enterprises'
    button:
      color: orange
      title: Contact Us
      href: '/demo/'
      outlined: true
    price:
      color: lavender
      title: Contact Us
      href: '/demo/'
    features:
      - name: Everything in Professional
      - name: Unlimited Guest Access
      - name: Single Tenant Managed Deployments
      - name: Multiple Git & Auth Providers
      - name: Custom Terms
      - name: Vendor Security Forms
    ctas:
      - color: orange
        href: /demo
        large: true
        title: Contact Us
collage:
  images:
    - src: /images/deutsche_bank.png
      alt: Deutsche Bank
    - alt: Chargify
      src: /images/chargify-new-logo.png
    - alt: Sendgrid
      src: /images/logo-sendgrid.png
    - alt: EA
      src: /images/ea.png
    - alt: TiVo
      src: /images/tivo.png
    - src: /images/logo_arkea_transparent.png
      alt: Arkea
    - src: /images/shopgate.png
      alt: Shopgate
  title: >-
    Trusted By Leading API First Companies
faq:
  title: Frequently Asked Questions
  description: Don't see your question? [Talk to a solutions engineer](https://stoplight.io/demo).

  questions:
    - question: Which users count toward the per-user pricing?
      description: >-
        All users that can log in to your Stoplight workspace except guest users count toward the per-user pricing.
        Guest users are part of the Professional and Enterprise plans only. Anonymous users accessing your documentation
        are not counted toward the per-user pricing and are part of all plans.
    - question: What is a project?
      description: >-
        A Stoplight project represents a Git repository.  Projects can contain multiple
        API descriptions, schemas, documentation, and even your source code.
      even: true
    - question: Which Git providers are supported by Stoplight?
      description: >-
        Stoplight currently integrates with GitHub, GitLab, and Bitbucket.
        Support for other Git providers like Azure DevOps Server will be coming soon.
        Please check out our [roadmap](https://stoplight.io/p/roadmap) for more information.
    - question: Do you offer annual billing?
      description: >-
        Yes! For annual billing, please contact us at sales@stoplight.io. The default billing cycle for Stoplight is monthly.
    - question: Do you offer discounts for Nonprofits or Open Source projects?
      description: >-
        Yes! We offer a free Starter plan for Open Source projects or organizations involved in COVID-19
        relief efforts, while Nonprofits can get our Starter plan at 50% off. Please contact us at
        support@stoplight.io to get started.
    - question: What happens when adding users mid-cycle?
      description: >-
        We’ll make a one-time, prorated charge to your credit card to cover new user accounts for
        the remainder of the current billing period. At the end
        of each monthly billing cycle, you will be billed for the upcoming month’s
        subscription-based on the exact number of Stoplight users.
      even: true
    - question: How secure is the Stoplight platform?
      description: >-
        Our hosted platform is monitored around the clock by a dedicated team of engineers.
        Our servers run on Google Kubernetes Engine and are configured in accordance with their recommended best practices,
        and all of the data we store is encrypted. Both the hosted platform and our on-premise artifacts receive security
        patches at least once a month (but often more). According to strict need-based policy, access to critical
        infrastructure and data is restricted to a handful of engineers. Our on-premise artifacts are designed to never
         transfer or store sensitive data in cleartext, support running as non-root or with random UID, and are compatible
         with Linux security systems like SELinux or AppArmor. We offer artifacts in several distributions and have experience
         working with enterprise security teams to meet their unique requirements.
actionBar:
  ctas:
    - color: blue2
      href: '/demo'
      large: true
      title: Contact Sales
      rightIcon: ['fad', 'arrow-right']
  enabled: true
  text: Need help picking a plan?
docPlans:
  ctas:
    - color: green
      href: '/demo'
      title: Get Started
      large: true
    - color: green
      href: '/demo'
      title: Get Started
      large: true
    - color: lavender
      href: '/demo'
      title: Get Started
      large: true
    - color: orange
      href: '/demo'
      title: Contact Us
      large: true
  title: Feature Breakdown by Plan
  plans:
    - title: Free
    - title: Starter
    - title: Professional
    - title: Enterprise
  categories:
    - category: Workspace
      features:
        - featureTitle: Max Users Allowed
          tooltip: Maximum number of members allowed in your workspace.
          plans:
            - title: Free
              display: 10
            - title: Starter
              display: no cap
            - title: Professional
              display: no cap
            - title: Enterprise
              display: no cap
        - featureTitle: Max Projects Allowed
          plans:
            - title: Free
              display: 5
            - title: Starter
              display: 50
            - title: Professional
              display: no cap
            - title: Enterprise
              display: no cap
        - featureTitle: Included Users
          plans:
            - title: Starter
              display: 5
            - title: Professional
              display: 10
            - title: Enterprise
              display: custom
        - featureTitle: Included Guests
          tooltip: Invite external stakeholders to view specific projects by using the guest role.
          plans:
            - title: Professional
              display: 50
            - title: Enterprise
              display: unlimited
    - category: API Design
      features:
        - featureTitle: Studio Web
          tooltip: Web based API designer with built in Git support, no installation required.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Studio Desktop
          tooltip: Work offline on your local filesystem with our cross platform desktop app.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: OpenAPI/JSON Schema Visual Designer
          tooltip: Create OpenAPI and JSON schema documents 10x faster with our form based designer.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Code Based Editing
          tooltip: Seamlessly switch from the form editor to the code editor for things like bulk replace, cut / paste, etc.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Schema Reuse
          tooltip: Pull models out of your OpenAPI documents and into their own dedicated files so that you can easily re-use them across OpenAPI documents.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Design Validation
          tooltip: Ensure that your OpenAPI syntax is valid.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Git Sync
          tooltip: Store your design files in your own Git repositories. Right alongside your code implementation, if you prefer!
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Documentation Editor
          tooltip: Manage markdown documentation right alongside your API designs, all from with in Stoplight Studio.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: OpenAPI Export
          tooltip: Export bundled or deferenced OpenAPI documents to use with other tooling.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Local Mock Servers
          tooltip: Studio Desktop can start local mock servers that are always up to date with your API design.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
    - category: API Mocking
      features:
        - featureTitle: Automatic Mock Servers
          tooltip: Use always up-to-date hosted and local mock severs from your documentation and during development.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Request Validation
          tooltip: Optional request validation to simulate errors when invalid request bodies are provided.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Configurable Response Codes
          tooltip: Force a request to respond with a particular response status code to aid in testing.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Static Responses
          tooltip: Configure mocks to respond with specific examples.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Dynamic Responses
          tooltip: Configure mocks to respond with responses that are dynamically generated from your schemas.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
    - category: API Documentation
      features:
        - featureTitle: Interactive API Docs
          tooltip: Automatically generate detailed API documentation for all your API designs including examples, validations, authentication, and a powerful try it out functionality.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: API Console (Try it out)
          tooltip: Let your users try out APIs from within the API documentation using their own parameters and credentials.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Rich Markdown Articles
          tooltip: Write reference guides and tutorials in rich markdown including code samples, callouts, and try it out.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Code Generation
          tooltip: Automatic client code samples in popular languages so that readers of your docs can get started quckly.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Custom Domains
          tooltip: Host your API documentation on a custom domain with minimal setup.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Automatic SSL
          tooltip: Automatically provision SSL for your hosted documentation.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Unlimited Documentation Views
          tooltip: Unlimited documentation views and API consumers for your public documentation.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Theming
          roadmap: true
          plans:
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Versioning
          roadmap: true
          plans:
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Remove Stoplight Branding
          tooltip: Remove the Powered by Stoplight badge from your documentation.
          plans:
            - Professional
            - Enterprise
    - category: API Visibility & Governance
      features:
        - featureTitle: Technical Knowledge Base
          tooltip: Central repository for all your designs, schemas, and documentation enabling visbility for your stakeholders.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Automatic Git Repo Analysis
          tooltip: Stoplight automatically analyzes and stays in sync with API descriptions, JSON Schemas, markdown articles, and images in your projects.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Search and Filter
          tooltip: Search and filter artifacts based on names, endpoints, schemas, and articles to promote visibility and reuse.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Star API Assets
          tooltip: Star important assets for easy discoverability and reuse.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Automatic Changelogs
          tooltip: View automatically generated changelogs for your API designs, schemas, and documentation.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Multi-Branch Support
          tooltip: Track multiple git branches to support versioning, reviews, and collaboration.
          roadmap: true
          plans:
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Dependency Graph
          tooltip: Visualize and track dependencies between your API assets.
          plans:
            - Professional
            - Enterprise
    - category: Consistency & Quality
      features:
        - featureTitle: API Style Guides
          tooltip: Create style guides for APIs to validate projects against organization standards.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Design Libraries
          tooltip: Reuse models across APIs by creating design libraries, ensuring reuse and consistency.
          roadmap: true
          plans:
            - Professional
            - Enterprise
        - featureTitle: Model Masking
          tooltip: Increase the flexibility of your design library by allowing users to include/exclude specific properties when they reference design library schemas.
          roadmap: true
          plans:
            - Professional
            - Enterprise
    - category: Integrations
      features:
        - featureTitle: Stoplight CLI
          tooltip: Use our CLI to push git repositories to Stoplight during your CI process, or from your local computer.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Cloud Git Providers
          tooltip: Connect your favorite Git provider like GitHub, GitLab or Bitbucket.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Self-hosted Git Providers
          tooltip: Connect seamlessly with enterprise Git providers.
          plans:
            - Professional
            - Enterprise
        - featureTitle: LDAP & SAML SSO
          tooltip: Enable single sign on (SSO) to integrate with your organization's existing authentication infrastructure.
          plans:
            - Professional
            - Enterprise
        - featureTitle: Multiple Git or Auth Providers
          tooltip: Helpful if your organization uses multiple Git or auth providers, such as Github and Bitbucket, etc.
          plans:
            - Enterprise
    - category: Access
      features:
        - featureTitle: User Management & RBAC
          tooltip: Invite API stakeholders with flexible roles and permissions.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Per-project User Access
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Project-level Visibility
          tooltip: Toggle between private, internal, and public to control baseline access to a project.
          plans:
            - Free
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Approved Email Domains
          tooltip: Streamline onboarding by allowing anybody with a verified email on the domains you choose to join your workspace.
          plans:
            - Starter
            - Professional
            - Enterprise
    - category: Support & Deployment
      features:
        - featureTitle: Credit Card Payment
          plans:
            - Starter
            - Professional
            - Enterprise
        - featureTitle: Invoicing (Annual plans only)
          plans:
            - Professional
            - Enterprise
        - featureTitle: Custom Payment Terms
          plans:
            - Enterprise
        - featureTitle: Single Tenant Deployment
          tooltip: Dedicated Stoplight instance for increased data security.
          plans:
            - Enterprise
        - featureTitle: Dedicated Support
          plans:
            - Enterprise
        - featureTitle: Custom EULA
          plans:
            - Enterprise
        - featureTitle: Vendor Security Forms
          plans:
            - Enterprise
