path: /pricing
color: blue
hero:
  title: Simple, Flexible Pricing
  subtitle: 'All plans include the entire Stoplight platform: API Modeling, Testing, Mocking, and Documentation'
plans:
  - title: 'Personal'
    description: 'For open source and individual use.'
    price: 'Free'
    features:
      - 'Unlimited projects'
    cta:
      name: Sign Up
      color: green
  - title: 'Team'
    description: For small teams and startups.
    price: '$24'
    unit: '/ user / month'
    features:
      - 'Up to 25 users'
      - 'Collaboration and discussions'
      - 'Access and role management'
    inheritedFeatures:
      - 'Unlimited projects'
    cta:
      name: Sign Up
      color: green
  - title: 'Enterprise'
    description: For enterprises with demanding requirements.
    price: 'Contact Us'
    features:
      - 'Unlimited users'
      - 'Hosted or on-premise'
      - 'Single sign-on'
      - 'Dedicated support'
    inheritedFeatures:
      - 'Unlimited projects'
      - 'Collaboration and discussions'
      - 'Access and role management'
    cta:
      name: Contact Us
      color: orange
      href: mailto:sales@stoplight.io
docs:
  title: 'Documentation Add-On'
  description: 'Combine OpenAPI with Markdown to create robust documentation for internal and external stakeholders. One click publish to host with Stoplight or download the static assets to host anywhere.'
  buttonText: 'Create Your First Documentation Hub'
  features:
    - title: 'OpenAPI, Markdown, Request Maker'
      plans:
        - 'Basic'
        - 'Essential'
        - 'Standard'
        - 'Pro'
    - title: 'Unlimited Visits'
      plans:
        - 'Basic'
        - 'Essential'
        - 'Standard'
        - 'Pro'
    - title: 'Publish to docs.stoplight.io'
      plans:
        - 'Basic'
        - 'Essential'
        - 'Standard'
        - 'Pro'
    - title: 'Publish to your domain'
      plans:
        - 'Essential'
        - 'Standard'
        - 'Pro'
    - title: 'Theming'
      plans:
        - 'Essential'
        - 'Standard'
        - 'Pro'
    - title: 'Build history & instant rollbacks'
      plans:
        - 'Essential'
        - 'Standard'
        - 'Pro'
    - title: 'Custom CSS'
      plans:
        - 'Standard'
        - 'Pro'
    - title: 'White label'
      plans:
        - 'Standard'
        - 'Pro'
    - title: 'Basic auth & Auth0 integrations'
      plans:
        - 'Standard'
        - 'Pro'
    - title: 'Download static HTML/CSS'
      plans:
        - 'Pro'
    - title: 'SAML single sign-on'
      plans:
        - 'Pro'
    - title: 'HTTP request OAuth token manager'
      plans:
        - 'Pro'
  plans:
    - title: 'Basic'
      price: 'Free'
    - title: 'Essential'
      price: '$69 / mo'
      domains: '1'
    - title: 'Standard'
      price: '$159 / mo'
      domains: '10'
    - title: 'Pro'
      price: '$349 / mo'
      domains: 'Unlimited'
