path: /pricing
hero:
  particles: true
  title: Stoplight Plans and Pricing
plans:
  - title: Free
    titleColor: green
    description: 'placeholder subtitle text if we want it'
    button:
      color: green
      title: Get Started
      href: 'https://stoplight.io/p/studio?utm_source=studio_landing&utm_medium=start_button&utm_campaign=dynamic_start'
    price:
      title: $0
    features:
      - name: Up to 10 users
      - name: Up to 5 projects
      - name: Native Git Sync
      - name: Private & Public Project Access
      - name: OAS3 Visual Designer
      - name: Hosted Mocking (1000)
      - name: JSON/YAML Linter
      - name: Project Style Guides
      - name: Technical Knowledge Base (Explorer)
      # - name: Changelog
  - title: Team
    titleColor: indigo
    description: 'placeholder subtitle text if we want it'
    button:
      color: indigo
      title: Get Started
      href: 'https://stoplight.io/p/studio?utm_source=studio_landing&utm_medium=start_button&utm_campaign=dynamic_start'
    price:
      title: $19
    features:
      - name: All features included in the Free plan
      - name: Up to 100 users
      - name: Up to 20 projects
      - name: Custom Domains
      - name: Theming
      - name: Custom Branding
      - name: Single Design Library
      - name: Guest Role
      - name: Hosted Mocking
      - name: Multi-Branch
  - title: Enterprise
    titleColor: purple
    description: 'placeholder subtitle text if we want it'
    button:
      color: purple
      title: Contact Us
      href: '/demo/'
    price:
      title: Custom Pricing
      button:
        color: purple
        title: Contact Us
        href: '/demo/'
    features:
      - name: All features included in the Team plan
      - name: Unlimited users
      - name: Unlimited projects
      - name: Model Masking
      - name: In & Outbound API Dependency Graph
      - name: Multiple Design Libraries
      - name: On-Premise Deployment
      - name: SSO & Authentication
      - name: Enterprise Terms & Support
      - name: Security Forms
      - name: Hubs project filters
      - name: Static IPs
      - name: Multiple Node Versions
collage:
  images:
    - alt: EA
      src: /images/ea.png
    - alt: Arkea
      src: /images/logo_arkea_transparent.png
    - alt: Chargify
      src: /images/chargify-new-logo.png
    - alt: Deutsche Bank
      src: /images/deutsche_bank.png
    - alt: Sendgrid
      src: /images/logo-sendgrid.png
    - alt: Shopgate
      src: /images/shopgate.png
    - alt: Spotify
      src: /images/spotify.png
    - alt: TiVo
      src: /images/tivo.png
    - alt: Zendesk
      src: /images/logo_zendesk.png
  title: >-
    Thousands of companies rely on Stoplight to streamline their API & Microservices
    workflow
faq:
  title: Frequently Asked Questions
  description: Don't see your question? [Talk to a solutions engineer](https://stoplight.io/demo).

  questions:
    - question: What is a Stoplight User?
      answer: >-
        A Stoplight user is any user able to log in to a Stoplight workspace.
    - question: What is a project?
      answer: >-
        A Stoplight project represents a git repository.
    - question: What happens when adding users mid-cycle?
      answer: >-
        We’ll make a one-time, prorated charge to your credit card to cover new user accounts for 
        the remainder of the current billing period. At the end 
        of each monthly billing cycle, you will be billed for the upcoming month's 
        subscription based on the exact number of Stoplight users.
    - question: Do you offer annual billing?
      answer: >-
        Yes, we offer annual billing. Please email sales@stoplight.io.
    - question: Do you offer discounts for Open Source projects?
      answer: >-
        Yes, we offer free team plans for Open Source projects. Please contact support@stoplight.io.
    - question: Do you offer discounts for non profits?
      answer: >-
        Yes, we offer 50% off team plans for non profits. Please contact support@stoplight.io.
actionBar:
  ctas:
    - color: accent
      href: '/demo'
      title: Speak with a Solutions Engineer
      rightIcon: ['fad', 'arrow-right']
  enabled: true
  text: Need help picking a plan?
docPlans:
  ctas:
    - color: green
      href: '/demo'
      title: Sign Up
      large: true
    - color: indigo
      href: '/demo'
      title: Sign Up
      large: true
    - color: purple
      href: '/demo'
      title: Contact Us
      large: true
  title: Feature Breakdown by Plan
  plans:
    - title: Free
    - title: Team
    - title: Enterprise
  categories:
    - category: API Design
      features:
        - featureTitle: Create unlimited APIs, Models, Endpoints, Articles, & Images
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: OpenAPI 3 form support
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Native git integration
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Create and switch between branches
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Create projects from an existing directory/folder on your computer
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Powerful search
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Dark theme
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Private share links
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Style guides
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Team
            - Enterprise
        - featureTitle: Design library
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Enterprise
        - featureTitle: Design library model masking
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Enterprise
    - category: API Design, Visbility & Governance
      features:
        - featureTitle: Git repo analysis & auto discovery
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Data filters
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Project search
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Workspace search
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: OpenAPI linter
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Dependency graph - inbound & outbound relationships
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Enterprise
    - category: API Docs
      features:
        - featureTitle: Unlimited published APIs
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Integrated 'Try it Out' API console
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Rich, markdown powered docs
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Export support
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Versioning support
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Complex JSON support
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Unlimited pageviews
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Build history and instant rollbacks
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Custom domains
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Team
            - Enterprise
        - featureTitle: Theming
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Team
            - Enterprise
        - featureTitle: Custom branding
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Team
            - Enterprise
        - featureTitle: Remove Stoplight logo
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Enterprise
        - featureTitle: Guest access
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Enterprise
    - category: API Mocking
      features:
        - featureTitle: Hosted mocking
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Integrated mocking support within API console
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Validate inputs, responses, webhooks & callbacks
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Automatic reload
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Free
            - Team
            - Enterprise
    - category: Supported Integrations
      features:
        - featureTitle: One external integration
          tooltip: GitHub, GitLab, Gitea, Bitbucket, Azure
          plans:
            - Free
            - Team
            - Enterprise
        - featureTitle: Unlimited external integrations
          tooltip: GitHub, GitLab, Gitea, Bitbucket, Azure
          plans:
            - Enterprise
    - category: Support
      features:
        - featureTitle: Dedicated customer success manager
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Enterprise
        - featureTitle: Invoicing options
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Enterprise
        - featureTitle: Bulk/scalable pricing
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Enterprise
    - category: Admin
      features:
        - featureTitle: Private & public project access
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Enterprise
        - featureTitle: SAML
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Enterprise
        - featureTitle: LDAP
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Enterprise
        - featureTitle: Domain capture
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Enterprise

    - category: Installation
      features:
        - featureTitle: On Premise
          tooltip: Tooltip content providing more detail about feature.
          plans:
            - Enterprise
