path: /api-design-guide-download
hero:
  title: Get Your Copy of the Stoplight API Design Guide
  subtitle: >-
    Get a copy of Stoplight's best practice guide for creating a design-first ethos within your organization.
  ctas:
    - title: Download Your Guide
      type: 'submit'
      submit:
        button:
          color: blue2
          title: Download Your Guide
        input:
          type: email
          placeholder: Your work email...
        formId: 'e6cb86b0-8b13-49b8-860a-0e717da5489d'
  forceTabsAlign: true
  tabs:
    - title: API Design Basics
      href: /api-design-guide/basics
    - title: API Design Tooling
      href: /api-design-guide/tooling
    - title: Understanding OpenAPI
      href: /api-design-guide/openapi
    - title: Download the Guide
      href: /api-design-guide-download
centerContent:
  description: >-
    Large enterprises embarking on Digital API transformation initiatives 
    are increasingly relying on API Design Management platforms in addition 
    to traditional API Management solutions to supercharge their business.


    Poor API designs lead to poor service implementations and documentation 
    which can slow down service delivery and negatively impact the ROI of 
    the initiative.


    Stoplight’s mission is to enable all stakeholders working with APIs to 
    be more productive. Developing good design first practices will minimize 
    future costs, speed up your time to market, and lead to more consistent, 
    higher quality microservice and IoT applications.
collage:
  title: TRUSTED BY LEADING API FIRST COMPANIES
  images:
    - src: /images/ea.png
      alt: EA
    - src: /images/logo_arkea_transparent.png
      alt: Arkea
    - src: /images/chargify-new-logo.png
      alt: Chargify
    - src: /images/deutsche_bank.png
      alt: Deutsche Bank
    - src: /images/logo-sendgrid.png
      alt: Sendgrid
    - src: /images/shopgate.png
      alt: Shopgate
    - src: /images/tivo.png
      alt: TiVo
testimonials:
  testimonials:
    - author: Tim Slagle
      company: Zoom
      image: /images/testimonials/tim_s.jpg
      quote: >-
        Our team roughly saves 15-20 hours a week. It makes it quicker to write, and the review process is quicker as well because we can go in and everybody can see the edits.  We're pretty impressed with Stoplight as a whole.
      role: Manager of Developer Advocacy
      # href: /case-studies/zoom-video/
    - author: 'Carlos Lozano '
      image: /images/carlos_testimonial.jpeg
      quote: >-
        When it comes to specification markup and documentation, the order of
        magnitude has gone from days to hours.
      role: 'Senior Enterprise Architect, GFT Group'
      # href: /case-studies/gft/
    - author: John Vajda
      image: /images/testimonials/john_vajda.jpeg
      quote: >-
        Stoplight has been a serious game changer for JumpCloud’s API development!
        We love all the rich design, documentation and testing features, which has
        enabled us to design awesome APIs for our customers.
      role: 'Product Manager, JumpCloud'
      # href: /case-studies
    - author: Felix Sargent
      company: MediaMath
      image: /images/felix_s.jpg
      quote: >-
        Stoplight provides a clean user interface and enables an engineering
        team to develop a compliant API with minimal difficulty. Other tools
        don't provide the same details, guard rails, and error validation that
        Stoplight provides.
      role: Director of Engineering
      # href: /case-studies/mediamath-video/
actionBar:
  enabled: false
meta:
  description: >-
    Get a copy of Stoplight's best practice guide for creating a 
    design-first ethos within your organization.
  favicon: /images/mark_light_bg.png
  image: /images/api-design-guide.png
  robots: 'noindex, nofollow'
  title: Get Your Copy of the Stoplight API Design Guide | Stoplight
  twitter:
    description: >-
      Get a copy of Stoplight's best practice guide for creating a 
      design-first ethos within your organization.
    image: /images/api-design-guide.png
    title: Get Your Copy of the Stoplight API Design Guide | Stoplight
    username: '@stoplightio'
