path: /partner-deal-registration
hero:
  title: Stoplight Partner Deal Registration
  subtitle: Working with a company that needs Stoplight? Provide the relevant information about your deal and our team will be in touch.
hubspot:
  formId: dc28e0a6-fe9c-4d7e-b6f6-966365a27577
  portalId: '4892910'
collage:
  title: TRUSTED BY LEADING API FIRST COMPANIES
  images:
    - src: /images/ea.png
      alt: EA
    - src: /images/logo_arkea_transparent.png
      alt: Arkea
    - src: /images/chargify-new-logo.png
      alt: Chargify
    - src: /images/deutsche_bank.png
      alt: Deutsche Bank
    - src: /images/logo-sendgrid.png
      alt: Sendgrid
    - src: /images/shopgate.png
      alt: Shopgate
    - src: /images/tivo.png
      alt: TiVo

meta:
  description: >-
    Working with a company that needs Stoplight? Provide the relavent information about your deal and our team will be in touch.
  favicon: /images/mark_light_bg.png
  title: Register Your Stoplight Partner Deal | Stoplight
  robots: 'noindex, nofollow'
  twitter:
    title: Register Your Stoplight Partner Deal | Stoplight
