path: /video/subscribe
title: Subscribe to Stoplight Webinars
subtitle: Watch & Learn
hero:
  particles: true
hubspot:
  formId: 132b647a-f85f-4bc0-bb0a-a019e30ba90e
  portalId: '4892910'
leftContent: {}
meta:
  description: Watch & Learn
  favicon: /images/mark_light_bg.png
  image: /images/aaa_blog_example.png
  robots: 'index, follow'
  title: Subscribe | Stoplight Webinars
  twitter:
    description: Watch & Learn
    image: /images/aaa_blog_example.png
    title: Subscribe | Stoplight Webinars
    username: '@stoplightio'
