path: /contact-us
color: grey-lighter
hero:
  title: Contact Us
  subtitle:
    Have a general question for Stoplight? Send us a message in the form. Need sales or support? Click on the buttons
    below.
  titleImage:
  aligned: left
  titleForm:
    formId: 7c71a3d0-fcd0-452f-981e-883c6cc86dd3
    portalId: '4892910'
  ctas:
    - title: Get Support
      href: 'https://support.stoplight.io/hc/en-us'
      color: blue2
    - title: Contact Sales
      href: 'https://stoplight.io/demo/'
      color: purple
  list:
    title:
    items:
      - name: Get in Touch
        summary: Get in touch with Stoplight
      - name: Don't Need Sales
        summary: Get answers for general questions
testimonials:
  testimonials:
    - author: Felix Sargent
      image: /images/felix_s.jpg
      quote: >-
        Stoplight provides a clean user interface and enables an engineering team to develop a compliant API with
        minimal difficulty. Other tools don't provide the same details, guard rails, and error validation that Stoplight
        provides.
      role: Director of Engineering, Media Math
    - author: Carlos Lozano
      image: /images/carlos_testimonial.jpeg
      quote: >-
        When it comes to specification markup and documentation, the order of magnitude has gone from days to hours.
      role: Senior Enterprise Architect, GFT Group
    - author: John Vajda
      image: /images/testimonials/john_vajda.jpeg
      quote: >-
        Stoplight has been a serious game changer for JumpCloud’s API development! We love all the rich design,
        documentation and testing features, which has enabled us to design awesome APIs for our customers.
      role: Product Manager, JumpCloud
    - author: Tim Slagle
      image: /images/testimonials/tim_s.jpg
      quote: >-
        Our team roughly saves 15-20 hours a week. It makes it quicker to write, and the review process is quicker as
        well because we can go in and everybody can see the edits.  We're pretty impressed with Stoplight as a whole.
      role: Manager of Developer Advocacy, Zoom
collage:
  images:
    - src: /images/deutsche_bank.png
      alt: Deutsche Bank
    - alt: Chargify
      src: /images/chargify-new-logo.png
    - alt: Sendgrid
      src: /images/logo-sendgrid.png
    - alt: EA
      src: /images/ea.png
    - alt: TiVo
      src: /images/tivo.png
    - src: /images/logo_arkea_transparent.png
      alt: Arkea
    - src: /images/shopgate.png
      alt: Shopgate
  title: >-
    Trusted By Leading API First Companies
meta:
  favicon: /images/mark_light_bg.png
  title: Find out how you can contact us | Stoplight
  description:
    Have a question or inquiry to make about APIs or Stoplight itself? Get in touch here to find out everything you need
    to know about working with us.
  twitter:
    title: Find out how you can contact us | Stoplight
