path: /demo
color: grey-lighter
hero:
  title: Accelerate API Development by 36%
  subtitle: Discover features found only in our Enterprise Platform
  titleImage:
  aligned: left
  titleDemo:
    formId: 7ae2bb42-67a6-4ee3-9ac5-ff21d87812ea
    portalId: '4892910'
  list:
    title: Talk to a Solutions Engineer
    items:
      - name: API Design
        summary: Learn how to model APIs 10x faster in open standards
      - name: Visibility
        summary: Increase consistency and visibility of your team's APIs
      - name: API Mocking
        summary: Enable front and back end to develop in parallel
testimonials:
  testimonials:
    - author: Felix Sargent
      image: /images/felix_s.jpg
      quote: >-
        Stoplight provides a clean user interface and enables an engineering team to develop a compliant API with
        minimal difficulty. Other tools don't provide the same details, guard rails, and error validation that Stoplight
        provides.
      role: Director of Engineering, Media Math
    - author: Carlos Lozano
      image: /images/carlos_testimonial.jpeg
      quote: >-
        When it comes to specification markup and documentation, the order of magnitude has gone from days to hours.
      role: Senior Enterprise Architect, GFT Group
    - author: John Vajda
      image: /images/testimonials/john_vajda.jpeg
      quote: >-
        Stoplight has been a serious game changer for JumpCloud’s API development! We love all the rich design,
        documentation and testing features, which has enabled us to design awesome APIs for our customers.
      role: Product Manager, JumpCloud
    - author: Tim Slagle
      image: /images/testimonials/tim_s.jpg
      quote: >-
        Our team roughly saves 15-20 hours a week. It makes it quicker to write, and the review process is quicker as
        well because we can go in and everybody can see the edits.  We're pretty impressed with Stoplight as a whole.
      role: Manager of Developer Advocacy, Zoom
collage:
  images:
    - src: /images/deutsche_bank.png
      alt: Deutsche Bank
    - alt: Chargify
      src: /images/chargify-new-logo.png
    - alt: Sendgrid
      src: /images/logo-sendgrid.png
    - alt: EA
      src: /images/ea.png
    - alt: TiVo
      src: /images/tivo.png
    - src: /images/logo_arkea_transparent.png
      alt: Arkea
    - src: /images/shopgate.png
      alt: Shopgate
  title: >-
    Trusted By Leading API First Companies
meta:
  description: >-
    Want to see how we could help your company and organization with our API Toolkit? Click here to request a demo and
    find out what we can do for you.
  favicon: /images/mark_light_bg.png
  title: Get a demo of our API Toolkit | Stoplight
  twitter:
    title: Get a demo of our API Toolkit | Stoplight
