title: Stoplight API Intersection Blog
subtitle: >-
    Musings on API design, testing, documentation, trends, and related technology.
path: /blog
tag: blog
hero:
  particles: true
  ctas:
    - title: Subscribe to the Newsletter
      type: 'submit'
      submit:
        button:
          color: purple
          title: Subscribe to the Newsletter
          href: '/blog/'
        input:
          type: email
          placeholder: Your email...
        formId: 'e58e3212-f08a-42fe-bbaa-29a21c27a3f5'
tabs:
  - href: /blog
    title: Latest
  - href: /blog/featured
    title: Featured
  - href: /blog/general
    title: General
  - href: /blog/api-design
    title: API Design
  - href: /blog/api-documentation
    title: API Documentation
  - href: /blog/api-testing
    title: API Testing
  - href: 'https://support.stoplight.io/hc/en-us/sections/360006632531-Releases'
    title: Changelog
actionBar:
  enabled: true
  text: Subscribe to the Stoplight API Intersection Newsletter
  ctas:
    - title: Subscribe to the Stoplight API Intersection Newsletter
      type: 'submit'
      submit:
        button:
          color: purple
          title: Subscribe
          href: '/blog/'
        input:
          type: email
          placeholder: Your email...
        formId: 'e58e3212-f08a-42fe-bbaa-29a21c27a3f5'
meta:
  description: >-
    Find out all you need to know about API design, testing, mocking, and
    documentation from the official Stoplight Blog, written by some of the best
    minds in the business.
  favicon: /images/mark_light_bg.png
  title: Latest Stoplight Blog Posts | Stoplight API Intersection
  twitter:
    title: Latest Stoplight Blog Posts | Stoplight API Intersection
    username: '@stoplightio'
pagination:
  enabled: true
