path: /blog/api-documentation
tag: blog-documentation
title: API Documentation
color: purple
tabs:
  - href: /blog/general
    title: General
  - href: /blog/api-design
    title: API Design
  - href: /blog/api-documentation
    title: API Documentation
  - href: /blog/api-testing
    title: API Testing
  - href: /blog/changelog
    title: Changelog
  - href: /blog
    title: Archive
actionBar:
  enabled: true
meta:
  favicon: /images/mark_light_bg.png
  title: API Documentation | Stoplight
  twitter:
    title: API Documentation | Stoplight
    username: '@stoplightio'
pagination:
  enabled: true
