path: /blog/api-design
tag: 'blog-design'
hero:
  subtitle: Discover & Educate
  title: Blog
  buttons:
    - title: API Design
      href: /blog/api-design
      icon: check-circle
    - title: API Documentation
      href: /blog/api-documentation
    - title: API Testing
      href: /blog/api-testing
    - title: Changelog
      href: /blog/changelog
    - title: Archive
      href: /blog
actionBar:
  enabled: true
meta:
  favicon: /images/mark_light_bg.png
  title: API Design | Stoplight
  twitter:
    title: API Design | Stoplight
    username: '@stoplightio'
pagination:
  enabled: true
