path: /blog/general
tag: blog-general
title: General
subtitle: ' '
color: purple
buttons:
  - href: /blog/blog-general
    title: General
  - href: /blog/api-design
    title: API Design
  - href: /blog/api-documentation
    title: API Documentation
  - href: /blog/api-testing
    title: API Testing
  - href: /blog/changelog
    title: Changelog
  - href: /blog
    title: Archive
actionBar:
  buttons: []
  enabled: true
meta:
  favicon: /images/mark_light_bg.png
  robots: 'index, follow'
  title: General | Stoplight
  twitter:
    title: General | Stoplight
    username: '@stoplightio'
pagination:
  enabled: true
