path: /video
tag: video
title: Stoplight Video Content
subtitle: Watch & Learn
color: grey-lighter
hero:
  ctas:
    - title: Subscribe to Stoplight Webinars
      type: 'submit'
      submit:
        button:
          color: blue2
          title: Subscribe to Stoplight Webinars
        input:
          type: email
          placeholder: Your email...
        formId: '0bd79a8c-f086-4e72-9641-a1255add5ac0'
actionBar:
  enabled: true
  text: Subscribe to Stoplight Webinars
  ctas:
    - title: Subscribe to Stoplight Webinars
      type: 'submit'
      submit:
        button:
          color: blue2
          title: Subscribe
        input:
          type: email
          placeholder: Your email...
        formId: '0bd79a8c-f086-4e72-9641-a1255add5ac0'
meta:
  description: Watch & Learn
  favicon: /images/mark_light_bg.png
  robots: 'index, follow'
  title: Videos and Webinars | Stoplight
  twitter:
    description: Watch & Learn
    title: Videos and Webinars | Stoplight
    username: '@stoplightio'
pagination:
  enabled: true
