path: /video
tag: video
title: Video Content | Stoplight API Intersection
subtitle: Watch & Learn
color: purple
tabs:
  - href: /video
    title: Videos
  - href: /video/subscribe
    title: Subscribe
actionBar:
  ctas:
    - href: /video/subscribe
      title: Subscribe
  enabled: true
  text: Subscribe to Stoplight Webinars
meta:
  description: Watch & Learn
  favicon: /images/mark_light_bg.png
  robots: 'index, follow'
  title: Videos and Webinars | Stoplight
  twitter:
    description: Watch & Learn
    title: Videos and Webinars | Stoplight
pagination:
  enabled: true
