path: /about
color: purple
hero:
  title: Hi There
  bowl: true
  subtitle: >-
    Stoplight is the best platform for an API design first approach. Easily create
    your design spec in any format. Then run tests, mock responses, and create
    beautiful documentation.
quotes:
  - author: Mike Bissett
    company: BurstSMS
    image: /images/customers/burst-sms.png
    quote: >-
      Great product, really does take the pain out of creating and maintaining
      swagger specs.
    role: CTO
team:
  description: >-
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
    non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    dfasdf
  members:
    - image: /images/team/marc-macleod.png
      name: Marc Macleod
      role: Founder and CEO
press:
  - description: Stoplight Launches Scenarios API Testing and Debugging Tool
    image: /images/press/programmableweb.png
    publication: Programmable Web
investors:
  - image: /images/investors/nextgen-venture-partners.png
    name: NextGen Venture Partners
career: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'
