hero:
  title: Best in class API Design, Docs, Mocking, and Testing
  subtitle: Stoplight leverages your OpenAPI files to drive the entire API development process.
  cta: Get Started Now
  bgColor: black
  cards:
    - title: API Designer
      subtitle: Use our visual designer to manage OpenAPI (Swagger) 10x faster.
      href: /api-design
      bgColor: blue
      icon:
        style: solid
        name: paint-brush
    - title: Technical Docs
      subtitle: Increase customer adoption with beautiful, functional documentation.
      href: /api-documentation
      bgColor: green
      icon:
        style: solid
        name: book
    - title: Contract Testing
      subtitle: Leverage OpenAPI to test, automate, and debug web APIs.
      href: /api-testing
      bgColor: orange
      icon:
        style: solid
        name: flask
    - title: API Mocking
      subtitle: Parallelize development with one click mock servers, powered by OpenAPI.
      href: /api-mocking
      bgColor: grey-darkest
      icon:
        style: solid
        name: server
platform:
  title: 'The Complete OpenAPI (Swagger) Toolkit'
  image: '/images/home-hero.png'
  description: >-
    Create OpenAPI documents 10x faster with no specialized knowledge required.
    Combine OpenAPI files with markdown to create beautiful documentation for internal and external
    stakeholders. Instantly turn any OpenAPI file into a mock server. Leverage contract testing to ensure that
    your single source of truth - OpenAPI - accurately describe your APIs.
customers:
  - '/images/customer_logos/ea.png'
  - '/images/customer_logos/arkea.png'
  - '/images/customer_logos/chargify.png'
  - '/images/customer_logos/deutsche_bank.png'
  - '/images/customer_logos/quicken.png'
  - '/images/customer_logos/sendgrid.png'
  - '/images/customer_logos/shopgate.png'
  - '/images/customer_logos/spotify.png'
  - '/images/customer_logos/tivo.png'
  - '/images/customer_logos/zendesk.png'
products:
  - title: 'API Designer'
    description: "With the Stoplight visual designer, you don't need to be an OpenAPI Specification expert. Involve everybody in the design process and manage your specifications 10x faster."
    image: '/images/editors/design_editor.png'
    link: 'http://docs.stoplight.io/modeling/introduction'
testimonials:
  - image: '/images/testimonials/kin_lane.jpeg'
    quote: “I feel like Stoplight has the potential to shift the landscape pretty significantly, something I haven't seen any API service provider do in a while.”
    company: ''
    author: 'Kin Lane'
    role: 'API Evangelist'
meta:
  favicon: '/favicons/favicon.ico'
  title: Stoplight
  siteName: Stoplight
  description: Stoplight, providing engineering teams with the best way to document,
    test, and build web APIs.
  url: https://stoplight.io
  image: '/images/home-hero.png'
  twitter:
    title: Stoplight
    description: Stoplight, providing engineering teams with the best way to document,
      test, and build web APIs.
    image: '/images/home-hero.png'
    username: '@stoplight'
