hero:
  title: Best in class API Design, Docs, Mocking, and Testing
  subtitle: Stoplight leverages your OpenAPI files to drive the entire API development process.
  cta:
    name: Get Started Now
  bgColor: black
  particles: true
  cards:
    - title: API Designer
      subtitle: Use our visual designer to manage OpenAPI (Swagger) 10x faster.
      href: /api-design
      bgColor: blue
      icon:
        style: solid
        name: paint-brush
    - title: Technical Docs
      subtitle: Increase customer adoption with beautiful, functional documentation.
      href: /api-documentation
      bgColor: green
      icon:
        style: solid
        name: book
    - title: Contract Testing
      subtitle: Leverage OpenAPI to test, automate, and debug web APIs.
      href: /api-testing
      bgColor: orange
      icon:
        style: solid
        name: flask
    - title: API Mocking
      subtitle: Parallelize development with one click mock servers, powered by OpenAPI.
      href: /api-mocking
      bgColor: grey-darkest
      icon:
        style: solid
        name: server
product:
  title: The Complete OpenAPI (Swagger) Toolkit
  image: /images/home-hero.png
  cta:
    name: Get Started Now
  description: >-
    Create OpenAPI documents 10x faster with no specialized knowledge required.
    Combine OpenAPI files with markdown to create beautiful documentation for internal and external
    stakeholders. Instantly turn any OpenAPI file into a mock server. Leverage contract testing to ensure that
    your single source of truth - OpenAPI - accurately describe your APIs.
customers:
  - '/images/customers/ea.png'
  - '/images/customers/arkea.png'
  - '/images/customers/chargify.png'
  - '/images/customers/deutsche-bank.png'
  - '/images/customers/quicken.png'
  - '/images/customers/sendgrid.png'
  - '/images/customers/shopgate.png'
  - '/images/customers/spotify.png'
  - '/images/customers/tivo.png'
  - '/images/customers/zendesk.png'
features:
  - title: API Designer
    image: /images/product/home-design.png
    description: >-
      With the Stoplight visual designer, you don't need to be an OpenAPI Specification expert.
      Involve everybody in the design process and manage your specifications 10x faster.
    href: http://docs.stoplight.io/modeling/introduction
  - title: API Documentation
    image: /images/product/home-docs.png
    description: >-
      Stoplight’s hosted documentation product supports custom domains, embedded docs,
      analytics integrations, custom themes, multiple layouts, and much more.
    href: http://docs.stoplight.io/modeling/introduction
  - title: API Mocking
    image: /images/product/home-mocking.png
    description: >-
      Turn your OpenAPI specifications into instant mock servers to allow your frontend and backend teams to work in parallel.
    href: http://docs.stoplight.io/modeling/introduction
  - title: API Testing
    image: /images/product/home-testing.png
    description: >-
      Run test scenarios directly from your terminal, with a single command. Integrates easily into your existing continuous integration process.
    href: http://docs.stoplight.io/modeling/introduction
testimonials:
  - image: /images/testimonials/kin_lane.jpeg
    quote: I feel like Stoplight has the potential to shift the landscape pretty significantly, something I haven't seen any API service provider do in a while.
    author: Kin Lane
    role: API Evangelist
