---
title: "Simple, Flexible Pricing"
description: "All plans include the entire Stoplight platform: API Modeling, Testing, Mocking, and Documentation"
plans:
  - title: "Open Source"
    price: "Free"
    features:
      - "Unlimited public projects"
      - "5 members"
  - title: "Team"
    price: "$24"
    priceMeta: "per member"
    features:
      - "Unlimited private projects"
      - "Up to 25 members"
  - title: "Enterprise"
    button:
      title: "Contact Us"
      link: "mailto:sales@stoplight.io"
    features:
      - "Hosted or On-Premise"
      - "Unlimited members"
      - "SAML single sign-on"
      - "Dedicated Support"
docs:
  title: "Documentation Add-ons"
  description: "Combine OpenAPI with Markdown to create robust documentation for internal and external stakeholders. One click publish to host with Stoplight or download the static assets to host anywhere."
  features:
    - title: "OpenAPI, Markdown, Request Maker"
      plans:
        - "Basic"
        - "Essential"
        - "Standard"
        - "Pro"
    - title: "Unlimited Visits"
      plans:
        - "Basic"
        - "Essential"
        - "Standard"
        - "Pro"
    - title: "Publish to docs.stoplight.io"
      plans:
        - "Basic"
        - "Essential"
        - "Standard"
        - "Pro"
    - title: "Publish to your domain"
      plans:
        - "Essential"
        - "Standard"
        - "Pro"
    - title: "Theming"
      plans:
        - "Essential"
        - "Standard"
        - "Pro"
    - title: "Build history & instant rollbacks"
      plans:
        - "Essential"
        - "Standard"
        - "Pro"
    - title: "Custom CSS"
      plans:
        - "Standard"
        - "Pro"
    - title: "White label"
      plans:
        - "Standard"
        - "Pro"
    - title: "Basic auth & Auth0 integrations"
      plans:
        - "Standard"
        - "Pro"
    - title: "Download static HTML/CSS"
      plans:
        - "Pro"
    - title: "SAML single sign-on"
      plans:
        - "Pro"
    - title: "HTTP request OAuth token manager"
      plans:
        - "Pro"
  plans:
    - title: "Basic"
      price: "Free"
    - title: "Essential"
      price: "$69 / mo"
      domains: "1"
    - title: "Standard"
      price: "$159 / mo"
      domains: "10"
    - title: "Pro"
      price: "$349 / mo"
      domains: "Unlimited"