backend:
  name: git-gateway
  branch: next
  accept_roles:
    - admin
    - editor
publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "netlify-cms/home.yaml"
        fields:
          - {label: "Heading", name: "heading", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Platform"
            name: "platform"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - label: "Features"
                name: "features"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
          - label: "Customers"
            name: "customers"
            widget: "list"
            field:
              - {label: Image, name: image, widget: image}
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Link", name: "link", widget: "string"}
          - label: "Quotes"
            name: "quotes"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Quote", name: "quote", widget: "text"}
              - {label: "Company", name: "company", widget: "string"}
              - {label: "Author", name: "author", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}

      - label: "Pricing"
        name: "pricing"
        file: "netlify-cms/pricing.yaml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Plans"
            name: "plans"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Price", name: "price", widget: "string", required: false}
              - {label: "Price Unit", name: "unit", widget: "string", required: false}
              - label: "Button"
                name: "button"
                widget: "object"
                required: false
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Link", name: "link", widget: "string"}
              - label: "Features"
                name: "features"
                widget: "list"
                field:
                  - {label: Features, name: feature, widget: string}
          - label: "Docs"
            name: "docs"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Features"
                name: "features"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - label: "Plans"
                    name: "plans"
                    widget: "list"
                    field:
                      - {label: Features, name: feature, widget: string}
              - label: "Plans"
                name: "plans"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Price", name: "price", widget: "string"}
                  - {label: "# of Domains", name: "domains", widget: "string", required: false}

      - label: "About"
        name: "about"
        file: "netlify-cms/about.yaml"
        fields:
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Background Image", name: "backgroundImage", widget: "image"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Mission", name: "mission", widget: "text"}
          - label: "Quotes"
            name: "quotes"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Quote", name: "quote", widget: "text"}
              - {label: "Company", name: "company", widget: "string"}
              - {label: "Author", name: "author", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}
          - label: "Team"
            name: "team"
            widget: "object"
            fields:
              - {label: "Description", name: "description", widget: "text"}
              - label: "Members"
                name: "members"
                widget: "list"
                fields:
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Role", name: "role", widget: "string"}
          - label: "Press"
            name: "press"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Publication", name: "publication", widget: "string"}
          - label: "Investors"
            name: "investors"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Name", name: "name", widget: "string"}
          - label: "Career Description"
            name: "career"
            widget: "text"

  - label: "Case Study"
    name: "case-studies"
    folder: "netlify-cms/case-studies"
    create: true
    slug: "{{slug}}"
    extension: "yaml"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Featured Highlights", name: "features", widget: "list"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "The Goal"
        name: "goal"
        widget: "object"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "The Solution"
        name: "solution"
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Image", name: "image", widget: "image"}
      - label: "The Results"
        name: "results"
        widget: "object"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Image", name: "image", widget: "image"}

  - label: "Product"
    name: "products"
    folder: "netlify-cms/products"
    create: true
    slug: "{{slug}}"
    extension: "yaml"
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "slogan", name: "slogan", widget: "text"}
      - {label: "description", name: "description", widget: "text"}
      - {label: "callToAction", name: "callToAction", widget: "text"}
      - {label: "signupText", name: "signupText", widget: "text"}
      - {label: "image", name: "image", widget: "image"}
      - label: "Feature List"
        name: "featureList"
        widget: "list"
        field:
          - {label: "title", name: "title", widget: "string"}
      - label: "Features"
        name: "features"
        widget: "list"
        fields:
          - {label: "title", name: "title", widget: "string"}
          - {label: "description", name: "description", widget: "text"}
          - {label: "image", name: "image", widget: "image"}