path: /deutsche-bank
title: 'Deutsche Bank'
description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed sapien orci. Nulla congue, sem at dapibus facilisis, purus metus hendrerit diam, tincidunt finibus eros libero eget ex.'
logo: /images/customers/deutsche-bank.png
features:
  - 'Feature 1'
  - 'Feature 2'
  - 'Feature 3'
goal:
  title: 'Goal title'
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed sapien orci. Nulla congue, sem at dapibus facilisis, purus metus hendrerit diam, tincidunt finibus eros libero eget ex.'
solution:
  title: 'API Design'
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed sapien orci. Nulla congue, sem at dapibus facilisis, purus metus hendrerit diam, tincidunt finibus eros libero eget ex.'
  image: '/images/individual-case-study/design-editor.png'
results:
  title: 'Results title'
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed sapien orci. Nulla congue, sem at dapibus facilisis, purus metus hendrerit diam, tincidunt finibus eros libero eget ex.'
meta:
  favicon: '/favicons/favicon.ico'
  title: Stoplight
  siteName: Stoplight
  description: Stoplight, providing engineering teams with the best way to document,
    test, and build web APIs.
  url: https://stoplight.io
  image: '/images/home-hero.png'
  twitter:
    title: Stoplight
    description: Stoplight, providing engineering teams with the best way to document,
      test, and build web APIs.
    image: '/images/home-hero.png'
    username: '@stoplight'
