path: /api-design
title: OpenAPI Designer
relatedTags:
  - blog-design
hero:
  title: Quality API Design at Blazing Speed
  subtitle: >-
    Adopt an API design-first approach by creating, prototyping, and sharing OpenAPI descriptions and JSON Schemas using a visual editor.
  titleImage: '/images/design/hero.svg'
  aligned: left
  ctas:
    - color: blue2
      href: https://stoplight.io/welcome
      large: true
      title: Get Started For Free
featureIconStrip:
  icons:
    - icon: pencil-ruler
      color: lavender
      title: Visual API Designer
    - icon: check-circle
      color: purple
      title: Style Guides
    - icon: server
      color: indigo
      title: Instant Mocking
    - icon: cubes
      color: lavender-dark
      title: Reusable Components
    - icon: eye
      color: blue2
      title: Live Docs Preview
    - image: /images/integrations/git.svg
      title: Git Integration
features:
  title: API Design-First Made Easy
  description: >-
    Start designing and documenting APIs using OpenAPI and JSON Schema. 
    Create and share prototypes with integrated mocking and live previews. 
    Collaborate using tried and tested Git workflows.
  features:
    - title: Design Faster with a Visual OpenAPI Editor
      shortName: Visual API Designer
      description: >-
        Empower your product managers, architects, and developers to create and prototype APIs without going into messy syntax. 
        Stoplight's visual editor has comprehensive OpenAPI and JSON Schema support.
      image: /images/design/editor.png
    - title: Ensure Consistency and Quality with Style Guides
      shortName: Style Guides
      description: >-
        Create high-quality API designs in line with industry best practices and organizational needs 
        by enforcing built-in or custom style guides. Style guides provide the flexibility to help 
        bring consistency without drilling down too hard on the current practices.
      image: /images/design/styleguides.svg
      isReversed: true
    - title: Bring Designs to Life with Automatic Mock Servers
      shortName: Instant Mocking
      description: >-
        Validate your designs with request and response validation. Design intelligently by getting 
        early feedback from internal and external stakeholders using customizable and always up-to-date mock servers.
      image: /images/design/mock.svg
    - title: Avoid Duplication by Reusing Components
      shortName: Reusable Components
      description: >-
        Organize better and avoid duplicates by reusing schemas across APIs. Easily update in one place to make changes across your APIs.
      image: /images/design/reuse.svg
      isReversed: true
    - title: Visualize Designs with Live Previews
      shortName: Live Docs Preview
      description: >-
        Put the consumer first by visualizing and trying out the API design and documentation within the API editor. Share with a single click when you're ready.
      image: /images/design/preview.svg
integrations:
  title: Collaborate Flexibly with Git Workflows
  shortTitle: Git Integration
  description: >-
    Work directly with API design artifacts on Git, fitting seamlessly into your current API design workflow.
  images:
    - alt: Azure DevOps
      src: /images/integrations/azure.svg
    - alt: GitHub
      src: /images/integrations/github.svg
    - alt: GitLab
      src: /images/integrations/gitlab.svg
    - alt: Bitbucket
      src: /images/integrations/bitbucket.svg
actionBar:
  ctas:
    - color: blue2
      href: https://stoplight.io/welcome
      title: Get Started For Free
      large: true
    - color: white
      href: '/studio'
      title: Download Studio Desktop
      large: true
      outlined: true
  enabled: true
  centered: true
  text: Ready to Start Designing Quality APIs?
  subtext: Available on Web and Desktop
solutionsNav:
  title: Explore the API Design Lifecycle
  icons:
    - icon: 'book-open'
      color: blue2
      title: Documentation
      href: /api-documentation
    - icon: chart-network
      color: lavender
      title: Visibility
      href: /api-visibility
    - icon: balance-scale
      color: purple
      title: Governance
      href: /api-governance
    - icon: user-friends
      color: yellow
      title: Collaboration
      href: /api-collaboration
    - icon: server
      color: indigo
      title: Mocking
      href: /api-mocking/
    - icon: code
      color: blue
      title: Development
      href: /api-development

meta:
  description: >-
    Design & build quality APIs with a collaborative, powerful, visual editor that allows you to prototype and share your API within minutes
  favicon: /images/mark_light_bg.png
  image: /images/design/hero.svg
  title: API Design | Stoplight OpenAPI Modeling & Designer API Tool Software
  robots: 'index, follow'
  twitter:
    description: >-
      Design & build quality APIs with a collaborative, powerful, visual editor that allows you to prototype and share your API within minutes
    image: /images/design/hero.svg
    title: API Design | Stoplight OpenAPI Modeling & Designer API Tool Software
    username: '@stoplightio'
  url: 'https://stoplight.io/api-design'
