path: /docs
title: Take Your API Beyond Static Documentation
relatedTags:
  - blog-documentation
hero:
  title: Take Your API Beyond Static Documentation
  particles: true
  subtitle: >-
    Generate instant, detailed, and interactive documentation with Stoplight Docs/Hub
  image:
    alt: Documentation
    src: /images/docs/landing.png
  ctas:
    - color: blue
      href: /studio
      title: Author in Studio
      large: true
      rightIcon: ['fad', 'arrow-right']
featureSection:
  title: Automated API Doc Generation
  description: >-
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  features:
    - description: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /images/docs/request-maker.png
      shortName: Avoid Integration Hand Holding
      title: Avoid Integration Hand Holding
    - description: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /images/docs/jsv.png
      shortName: Empower API Consumers
      title: Empower API Consumers
    - description: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /images/docs/jsv.png
      shortName: Custom Theming & Domains
      title: Custom Theming & Domains
  actionBar:
    enabled: true
    text: 'Ready to Publish?'
    ctas:
      - color: accent
        href: 'https://stoplight.io/studio'
        title: Get started with Studio
        rightIcon: ['fad', 'arrow-right']
      - color: grey-dark
        href: 'https://stoplight.io/p/login'
        title: Login with Github
        icon: ['fab', 'github']
meta:
  description: >-
    Generate instant, detailed, and interactive documentation with Stoplight Docs/Hub
  favicon: /images/mark_light_bg.png
  image: /images/docs/landing.png
  title: Free Hosted Technical Docs | Stoplight
  robots: 'noindex, follow'
  twitter:
    description: >-
      Generate instant, detailed, and interactive documentation with Stoplight Docs/Hub
    image: /images/docs/landing.png
    title: Free Hosted Technical Docs | Stoplight
    username: '@stoplightio'
