path: /docs
title: Take Your API Beyond Static Documentation
color: indigo
relatedTags:
  - blog-documentation
hero:
  title: Take Your API Beyond Static Documentation
  particles: true
  subtitle: >-
    Generate instant, detailed, and interactive documentation with Stoplight Docs/Hub
  image:
    alt: Documentation
    src: /images/docs/landing.png
  ctas:
    - color: green
      href: /studio
      title: Author in Studio
      icon: ['fad', 'pencil-alt']
      rightIcon: ['fad', 'arrow-right']

featureSection:
  title: Instant Doc Generation
  description: >-
    Stoplight Docs automatically renders API documentation from your design specification. 
    With the push of a button, create API documentation that instantly updates as your design specification changes.
  features:
    - description: >-
        Easily control your API’s documentation status with Stoplight Docs. 
        Quickly modify visibility, accessibility, and content as your API evolves to continuously refine the API consumer’s experience.
      image: /images/docs/request-maker.png
      shortName: Versatile Doc Management
      title: Versatile Doc Management

    - description: >-
        Integrate Stoplight Docs with the rest of your website. Maintain a consistent look and feel 
        across your organization’s website with custom theming and custom domains included in our Team and Enterprise packages.
      image: /images/docs/jsv.png
      shortName: Custom Theming & Custom Domain
      title: Custom Theming & Custom Domain

  actionBar:
    enabled: true
    text: 'Ready to Publish?'
    ctas:
      - color: accent
        href: 'https://stoplight.io/studio'
        title: Get started with Studio
      - color: grey-dark
        href: 'https://stoplight.io/p/login'
        title: Login with Github
        icon: ['fab', 'github']

meta:
  description: >-
    Generate instant, detailed, and interactive documentation with Stoplight Docs/Hub
  favicon: /images/mark_light_bg.png
  image: /images/docs/landing.png
  title: Free Hosted Technical Docs | Stoplight
  robots: 'noindex, follow'
  twitter:
    description: >-
      Generate instant, detailed, and interactive documentation with Stoplight Docs/Hub
    image: /images/docs/landing.png
    title: Free Hosted Technical Docs | Stoplight
    username: '@stoplightio'
