path: /explorer
title: A Powerful API Technical Knowledge Base
hero:
  particles: true
  image:
    alt: Stoplight Explorer
    src: /images/explorer/Explorer-placeholder-hero.png
  subtitle: >-
    Effectively search, filter, and understand complex API architectures with Stoplight Explorer.
  title: A Powerful API Technical Knowledge Base
  ctas:
    - title: Get Started with Explorer
      href: 'https://stoplight.io/p/studio?utm_source=studio_hero&utm_medium=web_button&utm_campaign=studio_landing'
      color: purple
      large: true
      rightIcon: ['fad', 'arrow-right']
featureSection:
  actionBar:
    ctas:
      - title: Get Started with Explorer
        href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-mac.dmg'
        color: green
        rightIcon: ['fad', 'arrow-right']
    enabled: true
    text: Ready to find what you're looking for?
  title: A Powerful Technical Knowledge Base For All APIs
  description: >-
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  features:
    - description: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /images/explorer/explorer-search-placeholder.png
      shortName: Know How Breaking Changes Impact Your API
      title: Know How Breaking Changes Impact Your API

    - description: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /images/explorer/dependency-placeholder.png
      shortName: Enable API Discovery & Reusability
      title: Enable API Discovery & Reusability

    - description: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /images/explorer/dependency-placeholder.png
      shortName: Find What You Need On Demand
      title: Find What You Need On Demand

meta:
  description: >-
    Navigate complex APIs easily with Stoplight Explorer.
  favicon: /images/mark_light_bg.png
  image: /images/studio/hero.png
  title: Stoplight Explorer | OpenAPI Design, Planning & Modeling Tool
  robots: 'noindex, follow'
  twitter:
    description: >-
      Navigate complex APIs easily with Stoplight Explorer.
    image: /images/studio/hero.png
    title: Stoplight Explorer | OpenAPI Design, Planning & Modeling Tool
    username: '@stoplightio'
