path: /api-mocking
title: API Mocking
relatedTags:
  - blog-mocking
hero:
  title: Design Better and Develop Faster
  subtitle: >-
    Go to market faster with high quality APIs using instant mock servers.
  titleImage: '/images/mocking/hero.svg'
  aligned: left
  ctas:
    - color: blue2
      href: https://stoplight.io/welcome
      large: true
      title: Get Started For Free
featureIconStrip:
  icons:
    - image: /images/integrations/openAPI.svg
      title: OpenAPI Support
    - icon: code
      color: blue2
      title: Early Feedback
    - icon: server
      color: indigo
      title: Parallel Development
    - icon: chart-network
      color: lavender
      title: Contract Testing
    - icon: paint-brush
      color: blue2
      title: Dynamic Mocking
features:
  title: Bring API Designs to Life with Mocking
  description: >-
    Visualize and get feedback on your API designs before spending time on development. 
    Let your frontend and backend teams develop in parallel with hosted mock servers. 
    Stoplight complements your workflow by instantly creating mock servers from API descriptions.
  features:
    - title: Instantly Convert OpenAPI Documents to Mocks
      shortName: OpenAPI Support
      description: >-
        Create mock servers from OpenAPI files automatically, with support for advanced OpenAPI features.
      image: /images/design/mock.svg
    - title: Get Early Feedback
      shortName: Early Feedback
      description: >-
        Get feedback from consumers and stakeholders on API designs before development using interactive protoypes. This allows you to act on feedback and align stakeholders promptly, ensuring 
        APIs fulfill consumer requirements and avoid unanticipated breaking changes later.
      image: /images/mocking/feedback.svg
      isReversed: true
    - title: Develop Simultaneously with Hosted Mock Servers
      shortName: Parallel Development
      description: >-
        Reduce time to market by letting Frontend and Backend teams develop simultaneously, without waiting for the development stage of the API to complete.
      image: /images/development/hostedmocks.svg
    - title: Validate and Test API Designs
      shortName: Contract Testing
      description: >-
        Validate requests and responses against your OpenAPI file. Stoplight mocks simulate real server behavior by automatically validating incoming request headers, query strings, and request bodies against your OpenAPI description.
      image: /images/development/validation.svg
      isReversed: true
    - title: Spin Up Life-like APIs with Dynamic Mocking
      shortName: Dynamic Mocking
      description: >-
        Testing against the same data over and over again is not the best way to build a robust integration. Dynamic mocking leverages fake data to simulate real server behavior by responding dynamically to requests.
      image: /images/mocking/dynamic.svg
actionBar:
  ctas:
    - color: blue2
      href: https://stoplight.io/welcome
      title: Get Started
      large: true
  enabled: true
  centered: true
  text: Develop Faster with Hosted Mocks.
solutionsNav:
  title: Explore the API Design Lifecycle
  icons:
    - icon: 'pencil'
      color: blue2
      title: Design
      href: /api-design
    - icon: code
      color: lavender
      title: Development
      href: /api-development
    - icon: chart-network
      color: indigo
      title: Visibility
      href: /api-visibility
    - icon: user-friends
      color: yellow
      title: Collaboration
      href: /api-collaboration
    - icon: balance-scale
      color: purple
      title: Governance
      href: /api-governance
    - icon: book-open
      color: blue2
      title: Documentation
      href: /api-documentation
meta:
  description: >-
    Go to market faster with high quality APIs using instant mock servers.
  favicon: /images/mark_light_bg.png
  image: /images/mocking/hero.svg
  title: Mocking | API Design & Planning Tool | Stoplight
  robots: 'index, follow'
  twitter:
    description: >-
      Go to market faster with high quality APIs using instant mock servers.
    image: /images/mocking/hero.svg
    title: Mocking | API Design & Planning Tool | Stoplight
    username: '@stoplightio'
  url: 'https://stoplight.io/api-mocking/'
