path: /mocking
title: Simple API Mocking
color: indigo
relatedTags:
  - blog-mocking
hero:
  particles: true
  image:
    alt: Stoplight Mocking
    src: /images/studio/hero.png
  subtitle: Automatic, hosted, and always in-sync. Never configure a mock server again.
  title: Simple API Mocking
  ctas:
    - href: '/studio'
      title: Try Out Mocking in Stoplight Studio
      color: green
      large: true
      rightIcon: ['fad', 'arrow-right']
    - href: '/open-source/prism'
      title: Prism Open Source Mock Server
      color: purple
      large: true
      rightIcon: ['fad', 'arrow-right']
featureSection:
  actionBar:
    text: 'Ready to mock your API?'
    enabled: true
    ctas:
      - href: '/studio'
        title: Get Started with Stoplight Studio
        rightIcon: ['fad', 'arrow-right']
  description: >-
    Instant and automatic, Stoplight Mocking spins up a server as soon as your API’s design 
    specification is published. And if any changes are made to your API, Stoplight Mocking 
    immediately reconfigures the mock server to always keep it up to date and in-sync.
  features:
    - description: >-
        Stoplight hosted mocking is designed for everyone to utilize. 
        Accelerate integrations across components and teams with a 
        life-like mock of your API’s design specification that doesn’t just live in your local development environment.
        API design.
      image: /images/mocking_instant.png
      shortName: Hosted Mocking for Everyone
      title: Hosted Mocking for Everyone
      titleURL: /mocking/server
    - description: >-
        Stoplight Mocking is configurable to behave in the way you want it to behave. 
        Directly from the client, set the response’s status code, enable or disable request validation, 
        and deactivate security schema check so that Stoplight Mocking helps you develop in all stages of the Software Development Life Cycle.
      image: /images/prism_dynamic.png
      shortName: Highly Versatile
      title: Highly Versatile
  title: Up in a Heartbeat
meta:
  description: >-
    Instant and automatic, Stoplight Mocking spins up a server as soon as your API’s design 
    specification is published.
  favicon: /images/mark_light_bg.png
  title: Simple API Mocking By Stoplight | Mock HTTP API Online
  twitter:
    description: >-
      Instant and automatic, Stoplight Mocking spins up a server as soon as your API’s design 
      specification is published.
    image: /images/mocking_instant.png
    title: Simple API Mocking By Stoplight | Mock HTTP API Online
    username: '@stoplightio'
