path: /open-source/prism
title: Prism - Open-Source HTTP Mock & Proxy Server | Stoplight
color: purple-darker
relatedTags:
  - blog-mocking
hero:
  subtitle: Accelerate API development with realistic mock servers, powered by OpenAPI documents.
  title: Prism, an Open-Source HTTP Mock & Proxy Server
  particles: true
  ctas:
    - color: green
      href: 'https://github.com/stoplightio/prism'
      title: GitHub
      icon: ['fab', 'github']
    - color: indigo
      href: 'https://youtube.com/watch?v=nZM26knV_ec'
      title: Watch the Video
      icon: ['fad', 'video']
      type: video
    - color: indigo
      href: 'https://stoplight.io/p/docs/gh/stoplightio/prism'
      title: Read the Docs
      icon: ['fad', 'book-open']
featureSection:
  actionBar:
    ctas:
      - href: 'https://stoplight.io/p/docs/gh/stoplightio/prism'
        title: Get Started with Prism
    enabled: true
    text: Do you want to mock your API in minutes?

  title: Work with your API before you write any code
  description: >-
    Prism is an open-source HTTP mock server that can mimic your API's behavior as if you already built it. Mock HTTP servers are generated from your OpenAPI v2/v3 (formerly known as Swagger) documents.
  features:
    - description: >-
        The waterfall model does not work well for building APIs. Learning at the very end what your
        potential consumers think about your software can be source of huge problems.
        With Prism you can move the feedback stage to the design phase of your API by
        providing a real server to use and play with.
      image: /images/prism_mocking.png
      shortName: Quick Iterations
      title: Quickly iterate on your API

    - description: >-
        Static examples in mock APIs can bias the way you write the code and test the API.
        Prism can generate dynamic random examples based on your API description,
        so the examples are always valid.
      image: /images/prism_dynamic.png
      shortName: Dynamic Examples
      title: Generate dynamic examples

    - description: >-
        Prism validates both request and response data. If you have an
        invalid example in the specification, Prism will let you know; if your request is not compliant with the rules
        of your API specification, Prism will return an error message. It will never yell to you, we promise.
      image: /images/prism_validation.png
      shortName: Validation
      title: Validate input and output

    - description: >
        Requests and responses take care of a lot of API interactions, but what 
        about callbacks? OpenAPI v3.0 allows API designers to define callbacks, 
        and construct a URL to fire a payload at, so Prism will too. Notice HTTP
        callbacks coming in, allowing you to attempt to integrate them before the
        API has even been built.
      image: /images/callbacks.jpg
      shortName: Callbacks
      title: Mocking Callbacks

    - description: >
        Identify discrepancies between the OpenAPI document and target API to
        help frontend developers integrating with your API. The proxy can also
        be enabled in staging or any other pre-production environment, to ensure
        OpenAPI documents and code stay in sync.
      image: /images/prism_science.jpg
      shortName: Proxy
      title: Validation Proxy
      
meta:
  description: Accelerate API development with realistic mock servers powered by API descriptions
  favicon: /images/mark_light_bg.png
  image: /images/prism_example.png
  title: Prism | Open-Source HTTP Mock and Proxy Server
  twitter:
    description: Accelerate API development with realistic mock servers powered by API descriptions
    image: /images/prism_example.png
    title: Prism | Open-Source HTTP Mock and Proxy Server
    username: '@stoplightio'
