path: /solutions/mocking
title: API Mocking
relatedTags:
  - blog-mocking
hero:
  particles: true
  subtitle: Reduce time to market with instant mock servers by designing intelligently and optimizing API development.
  title:  Design Better - Develop Faster
  ctas:
    - href: '/welcome'
      title: Get Started with Stoplight
      color: blue2
      large: true
      rightIcon: ['fad', 'arrow-right']
featureSection:
  actionBar:
    text: 'Ready to mock your API?'
    enabled: true
    ctas:
      - href: '/welcome'
        title: Get Started with Stoplight
        large: true
        rightIcon: ['fad', 'arrow-right']
        color: blue2
  description: >-
    Visualize and get feedback on your API designs before spending time on development. 
    Let your Frontend and Backend teams develop in parallel with hosted mock servers. 
    Stoplight complements your workflow by instantly creating mock 
    servers from API descriptions.
  features:
    - description: >-
        Convert OpenAPI descriptions into mock servers with extensive support for OpenAPI features. 
        Use specific examples form within the description or consume dynamic responses.
      image: /images/mocking/openapi-mock.png
      shortName: OpenAPI Support
      title: Instantly Convert OpenAPIs to Mocks 
      titleURL:
    - description: >-
        With an interactive and life-like mock of APIs, 
        you can begin to get feedback from consumers and stakeholders on  API designs before development allowing 
        you to act on feedback immediately and align stakeholders quickly. 
        This ensures APIs fulfill consumer requirements and helps avoid unanticipated breaking changes later.
      image: /images/mocking/mocking-feedback.png
      shortName: Early Feedback
      title: Get Early Feedback
      titleURL:
    - description: >-
        Reduce time to market by letting frontend and backend teams develop simulatenously without 
        waiting for the development stage of the API to complete. 
      image: /images/mocking/hosted-mocks.png
      shortName: Parallel Development
      title:  Develop Simultaneously with Hosted Mock Servers
      titleURL:
    - description: >-
        Validate requests and responses against your OpenAPI document. 
        Stoplight mocks simulate real server behavior by automatically validating incoming request headers, query strings, 
        and request bodies against your OpenAPI document.  
      image: /images/mocking/validate-prism.png
      shortName: Request & Response Validation
      title: Validate and Test API Designs
      titleURL: 
    - description: >-
        Testing against the exact same piece of data over and over again is not the best way to build a robust integration. 
        Dynamic mocking leverages fake data to simulate real server behaviour by responding dynamically to requests.
      image: /images/mocking/dynamic-mocking.png
      shortName: Dynamic Mocking
      title: Spin Up Life-like APIs with Dynamic Mocking
      titleURL: 
  title: Bring API Designs to Life with Mocking
meta:
  description: >-
    Instant and automatic, Stoplight Mocking spins up a server as soon as your API’s design 
    specification is published.
  favicon: /images/mark_light_bg.png
  title: Simple API Mocking By Stoplight | Mock HTTP API Online
  twitter:
    description: >-
      Instant and automatic, Stoplight Mocking spins up a server as soon as your API’s design 
      specification is published.
    image: /images/mocking_instant.png
    title: Simple API Mocking By Stoplight | Mock HTTP API Online
    username: '@stoplightio'
