path: /api-design
title: API Design
relatedTags:
  - blog-design
hero:
  particles: true
  subtitle: >-
    Easily adopt an API design-first approach by creating, prototyping, and sharing OpenAPIs and JSON schemas using a visual editor in minutes.
  title: Design Quality APIs Faster
  ctas:
    - href: '/welcome'
      title: Get Started For Free
      color: blue2
      large: true
      rightIcon: ['fad', 'arrow-right']
featureSection:
  actionBar:
    ctas:
      - href: '/welcome'
        title: Get Started with Stoplight
        large: true
        color: blue2
        rightIcon: ['fad', 'arrow-right']
    enabled: true
    text: Ready to Start Designing APIs?
  description: >-
    Start designing and documenting APIs in Stoplight Studio using OpenAPI and JSON schema. 
    Create and share prototypes on the go with integrated mocking and live previews. 
    Collaborate using tried and tested Git workflows.
  features:
    - description: >-
        Empower your product managers, architects, and developers to create and prototype APIs without going into messy syntax. 
        Stoplight’s visual editor comes with comprehensive OpenAPI and JSON Schema support.
      image: /images/design/studio.png
      shortName: Visual OpenAPI Editor
      title: Design Faster with a Visual OpenAPI editor
      titleURL: 
    - description: >-
        Create high-quality API designs in line with industry best practices and organizational needs by enforcing built-in or 
        custom style guides. Style guides come with the flexibility to help bring consistency without drilling down too hard on the current practices.
      image: /images/governance/style-guide.png
      shortName: Style Guides
      title: Ensure Consistency and Quality with Style Guides
      titleURL:
    - description: >-
        Validate your designs with request and response validation. Design intelligently by getting early feedback from internal and external stakeholders using customizable and always up-to-date 
        mock servers.    
      image: /images/design/mocking.png
      shortName: Mocking
      title: Bring Designs to Life with Automatic Mock Servers
      titleURL:
    - description: >-
        Organize better and avoid duplicates by reusing schemas across APIs. Easily update in one place to make changes across your APIs.    
      image: /images/design/reuse-schemas.png
      shortName: Reuse Components
      title: Avoid Duplication by Reusing Components
      titleURL:
    - description: >-
       Put the consumer first by visualizing and trying out the API design and documentation within the API editor. Share with a single click when you're ready.
      image: /images/design/docs-studio.png
      shortName: Documentation Preview
      title: Visualize Designs with Live Previews
      titleURL:
    - description: >-
        Share designs easily with internal and external stakeholders with varying permissions while working with tried and tested Git workflows.     
      image: /images/design/git-workflows.png
      shortName: Git Workflows
      title: Collaborate flexibly with Git Workflows
      titleURL:

  title: API Design-First Made Easy
meta:
  description: >-
    Create more complete, robust, and maintainable APIs with a design first approach.
  favicon: /images/mark_light_bg.png
  image: /images/design_feature_3.png
  title: REST API Design & Planning Tool | REST API Modeling & Designer Tool
  twitter:
    description: >-
      Create more complete, robust, and maintainable APIs with a design first approach.
    image: /images/design_feature_3.png
    title: REST API Design & Planning Tool | REST API Modeling & Designer Tool
    username: '@stoplightio'
