path: /solutions/governance
title: API Governance
color: lavender-darker
relatedTags:
  - blog-governance
hero:
  particles: true
  subtitle: Govern APIs at scale with an always in sync central repository of API designs, schemas, and documentation.
  title: Maintain a central source of truth
  ctas:
    - href: '/welcome'
      title: Get Started with Stoplight
      color: green
      large: true
      rightIcon: ['fad', 'arrow-right']
    - href: '/pricing'
      title: View Plans and Pricing
      color: blue2
      large: true
      rightIcon: ['fad', 'arrow-right']
featureSection:
  actionBar:
    text: 'Ready to bring order to your APIs?'
    enabled: true
    ctas:
      - href: '/welcome'
        title: Get Started with Stoplight
        rightIcon: ['fad', 'arrow-right']
  description: >-
    Aggregate all your API descriptions, schemas, and documentation in a central repository laying the groundwork for deduplication, reuse and governance.
  features:
    - description: >-
         Make APIs that have long become lost in the organization available for developers to use and champions to govern, helping keep documentation up-to-date, avoid duplications, and remove inconsistencies.
      image: /images/governance/explore.png
      shortName: Find obscure APIs
      title: Find obscure APIs
      titleURL: 
    - description: >-
        Deliver consistent API design and documentation across the organization by enforcing style guides and helping API designers and technical writers find artifacts for reference.
      image: /images/governance/style-guide.png
      shortName: Promote consistency
      title: Promote consistency
      titleURL: 
    - description: >-
        Avoid breaking changes and plan versions by tracking and visualizing inbound and outbound dependencies between API artifacts to keep track of how changes may affect other dependent services.
      image: /images/governance/dependencies.png
      shortName: Visualize Dependencies
      title: Visualize Dependencies
      titleURL:
    - description: >-
        Inform consumers about changes proactively by tracking changes of all API artifacts. Keep everything up to date by tracking changes between dependent artifacts.
      image: 
      shortName: Track Changes
      title: Track Changes
      titleURL:
    - description: >-
        Avoid reinventing the wheel. Star important assets, to enable easy discovery of API artifacts for reuse in future designs.
      image: /images/governance/reuse.png
      shortName: Encourage reuse
      title: Encourage reuse
      titleURL:
    - description: >-
        With a good view of the current state of design and documentation, build an effective governance strategy without drilling down too hard on the current practices.
      image: /images/governance/explorer-2.png
      shortName: Govern with Agility
      title: Govern with Agility
      titleURL:
  title: Bring visbility to APIs and Documentation
meta:
  description: >-
    Achieve API Quality & Governance by practically enforcing API consistency and standardization.
  favicon: /images/mark_light_bg.png
  title: Simple API Governance By Stoplight | API Governance and Administration
  twitter:
    description: >-
      Achieve API Quality & Governance by practically enforcing API consistency and standardization.
    image: /images/mocking_instant.png
    title: Simple API Governance By Stoplight | API Governance and Administration
    username: '@stoplightio'