path: /solutions/visibility
title: API Visibility
relatedTags:
  - blog-visibility
  - blog-design
hero:
  particles: true
  subtitle: >-
    As the number of APIs increase, it becomes difficult to track the services available to you and your team. Aggregate all your API descriptions, schemas, and documentation in a central repository, laying the groundwork for deduplication, reuse, and governance.
  title: Maintain a Central Source of Truth
  ctas:
    - href: '/welcome'
      title: Get Started with Stoplight
      color: blue2
      large: true
      rightIcon: ['fad', 'arrow-right']
    - href: '/pricing'
      title: View Plans and Pricing
      color: blue2
      large: true
      outlined: true
featureSection:
  actionBar:
    ctas:
      - href: '/welcome'
        title: Get Started For Free
        large: true
        color: blue2
        rightIcon: ['fad', 'arrow-right']
    enabled: true
    text: Ready to Start Designing APIs?
  description: >-
    As the number of APIs increase, it becomes difficult to track the services available 
    to you and your team. Aggregate all your API descriptions, schemas, and documentation 
    in a central repository, laying the groundwork for deduplication, reuse and governance. 
  features:
    - description: >-
        Create a collection of up-to-date API design assets like OpenAPIs, JSON Schemas, and 
        Documentation from your favorite VCS (GitHub, GitLab, Gitea, and Bitbucket). Search, 
        reuse, and govern obscure APIs helping align stakeholders on the current state of documentation 
        and design within the organization. 
      image: /images/explorer/api-catalog.png
      shortName: API Catalog
      title: Enable Discovery with a Central API Catalog
      titleURL: 
    - description: >-
        Use Stoplight Explorer to search API artifacts across the organization powered by filters 
        that make navigation a breeze.  
      image: /images/governance/explore.png
      shortName: Search & Filter
      title: Search and Filter API Artifacts
      titleURL: 
    - description: >-
        Use granular roles and permissions to expose on a need only basis. Bring in stakeholders 
        and partners to collaborate on projects that are in their scope.   
      image: /images/docs/api-catalog.png
      shortName: Roles and Permissions
      title: Personalized View for Every Role
      titleURL: 
    - description: >-
        Avoid breaking changes and plan versions by tracking and visualizing inbound and outbound dependencies between API artifacts to keep track of how changes may affect other dependent services.
      image: /images/governance/dependencies.png
      shortName: Visualize Dependencies
      title: Visualize Dependencies
      titleURL:
    - description: >-
        Stay up to date with automatic changelogs for all API design artifacts. Inform consumers about changes proactively and avoid out of date dependencies. 
      image: 
      shortName: Changelogs
      title: Track Changes
      titleURL:
    - description: >-
        Star essential assets, to enable easy discovery of relevant API artifacts by stakeholders. 
      image: /images/governance/reuse.png
      shortName: Star and Reuse
      title: Star What's Important
      titleURL:
  title: Never Lose Sight of Your APIs Again
meta:
  description: >-
    Create more complete, robust, and maintainable APIs with a design first approach.
  favicon: /images/mark_light_bg.png
  image: /images/design_feature_3.png
  title: REST API Design & Planning Tool | REST API Modeling & Designer Tool
  twitter:
    description: >-
      Create more complete, robust, and maintainable APIs with a design first approach.
    image: /images/design_feature_3.png
    title: REST API Design & Planning Tool | REST API Modeling & Designer Tool
    username: '@stoplightio'
