path: /solutions/collaboration
title: API Collaboration
relatedTags:
  - blog-collaboration
hero:
  particles: true
  subtitle: Improve alignment and collaboration by bringing internal and external stakeholders together in a single platform.
  title: Build APIs Together
  ctas:
    - href: '/welcome'
      title: Get Started with Stoplight
      color: blue2
      large: true
      rightIcon: ['fad', 'arrow-right']
    - href: '/pricing'
      title: View Plans and Pricing
      color: blue2
      large: true
      outlined: true
featureSection:
  actionBar:
    text: 'Ready to collaborate with your team?'
    enabled: true
    ctas:
      - href: '/welcome'
        title: Get Started with Stoplight
        large: true
        rightIcon: ['fad', 'arrow-right'] 
        color: blue2
  features:
    - description: >-
        Scale seamlessly by bringing all internal (Product Managers, Developers, Designers, Architects and Technical Writers) 
        and External Stakeholders in a single place with flexible roles and permissions. 
      image: /images/workspaces/permissions.png
      shortName: Roles and Permissions
      title: Collaborate Securely
      titleURL:
    - description: >-
        Invlove external partners and customers early in the development cycle by giving access to specfic projects using the Guest Role.
      image: /images/workspaces/invites.png
      shortName: Guest Access
      title: Involve Partners
      titleURL:
    - description: >-
        Work on your projects privately before sharing them with the organization or the world. It's as simple as changing a setting. 
      image: /images/workspaces/project-permissions.png
      shortName: Private/Public Projects
      title: Create Privately - Share Publically
      titleURL: 
    - description: >-
        Collaborate on API designs and documentation in a central source of truth using Git (Not Git-Like),
        seamlessly fitting into existing workflows.
      image: /images/design/git-workflows.png
      shortName: Git Workflows
      title: Integrate Seamlessly with Git Workflows 
      titleURL:
meta:
  description: >-
    Achieve API Quality & Governance by practically enforcing API consistency and standardization.
  favicon: /images/mark_light_bg.png
  title: Simple API Governance By Stoplight | API Governance and Administration
  twitter:
    description: >-
      Achieve API Quality & Governance by practically enforcing API consistency and standardization.
    image: /images/mocking_instant.png
    title: Simple API Governance By Stoplight | API Governance and Administration
    username: '@stoplightio'