path: /solutions/governance
title: API Governance
relatedTags:
  - blog-governance
  - blog-visibility
hero:
  particles: true
  subtitle: Govern APIs at scale with an always in sync central repository of API designs, schemas, and documentation.
  title: Consistent and Quality APIs at Scale
  ctas:
    - href: '/welcome'
      title: Get Started with Stoplight
      color: green
      large: true
      rightIcon: ['fad', 'arrow-right']
    - href: '/pricing'
      title: View Plans and Pricing
      color: blue2
      large: true
      rightIcon: ['fad', 'arrow-right']
featureSection:
  actionBar:
    text: 'Ready to bring order to your APIs?'
    enabled: true
    ctas:
      - href: 'https://stoplight.io/welcome'
        title: Get Started with Stoplight
        rightIcon: ['fad', 'arrow-right']
  description: >-
    Aggregate and track all your API design artifacts in a central repository, laying the groundwork for deduplication, reuse and governance. 
    Build an effective governance strategy that compliments your organization's current practices with clear view of the current state of design and documentation.
  features:
    - description: >-
         Make APIs that have long become lost in the organization available for developers to use and champions to govern, helping keep documentation up-to-date, avoid duplications, and remove inconsistencies.
      image: /images/governance/explore.png
      shortName: Find Obscure APIs
      title: Find Obscure APIs
      titleURL: 
    - description: >-
        Deliver consistent API design and documentation across the organization by enforcing built-in or custom style guides. Help API designers and technical writers find design artifacts for reference.
      image: /images/governance/style-guide.png
      shortName: Style Guides
      title: Build Consistent APIs with Style Guides
      titleURL: 
    - description: >-
        Avoid breaking changes and plan versions by tracking and visualizing inbound and outbound dependencies between API artifacts to keep track of how changes may affect other dependent services.
      image: /images/governance/dependencies.png
      shortName: Visualize Dependencies
      title: Visualize Dependencies
      titleURL:
    - description: >-
        Inform consumers about changes proactively by tracking changes of all API artifacts. Keep everything up to date by tracking changes between dependent artifacts. Avoid reinventing the wheel. Star important assets, to enable easy discovery of API artifacts for reuse in future designs.
      image: /images/governance/reuse.png
      shortName: Encourage Reuse
      title: Encourage Reuse
      titleURL:
    - description: >-
        Use granular roles and permissions to expose on a need only basis. Bring in stakeholders 
        and partners to collaborate on projects that are just in their scope. Audit activity across
        teams to maintain sanity. 
      image: /images/workspaces/permissions.png
      shortName: Roles and Permissions
      title: Manage Multiple API Teams
      titleURL: 
  title: Govern with Agility
meta:
  description: >-
    Achieve API Quality & Governance by practically enforcing API consistency and standardization.
  favicon: /images/mark_light_bg.png
  title: Simple API Governance By Stoplight | API Governance and Administration
  twitter:
    description: >-
      Achieve API Quality & Governance by practically enforcing API consistency and standardization.
    image: /images/mocking_instant.png
    title: Simple API Governance By Stoplight | API Governance and Administration
    username: '@stoplightio'