path: /studio
title: Stoplight Studio
relatedTags:
  - blog-design
hero:
  subtitle: >-
    Create, collaborate, and prototype APIs with Stoplight Studio
  title: Effortless API Design
  ctas:
    - title: On the Web
      href: 'https://stoplight.io/welcome/create'
      icon: ['fad', 'browser']
      color: blue2
      large: true
    - title: Mac App
      href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-mac.dmg'
      icon: ['fab', 'apple']
      color: purple
      filename: studio-mac
      large: true
    - title: Windows App
      href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-win.exe'
      icon: ['fab', 'windows']
      color: indigo
      filename: studio-windows
      large: true
    - title: Linux App
      href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-linux-x86_64.AppImage'
      icon: ['fab', 'linux']
      color: lavender
      filename: studio-linux
      large: true
features:
  description: >-
    Start designing your API in minutes. Use the [OpenAPI
    Specification](/api-design-guide/openapi/) (formerly known as Swagger) with
    Stoplight Studio to design consistent and standardized HTTP APIs for your
    organization. Without writing any code, model complex APIs faster than ever
    while simultaneously getting feedback on your prototypes with our
    [instant mock servers](/api-mocking/).
  features:
    - description: >-
        Design an API with speed and efficiency from scratch. Stoplight Studio
        decreases the learning curve so you don’t need to be an OpenAPI
        expert to create first-class API designs. Describe endpoints, headers,
        bodies, multiple responses, query string parameters, shared models, and
        examples, and much more for complex APIs.
      image: /images/design/editor.png
      shortName: OpenAPI Visual Editor
      title: 'A Powerful OpenAPI v2 & v3 Visual Editor'
    - description: >-
        Instantly prototype and collaborate on your API design with our integrated,
        instant Mock Servers, powered by [Prism](/prism/). A mock API simulates the
        behavior of a real API allowing collaboration and feedback on your API
        design. Automatically update to match your API design. Mock a single API
        or multiple APIs at once.
      image: /images/design/mock.svg
      shortName: Mock Servers
      title: 'Instant Mock Servers'
      isReversed: true
      ctas:
        - color: blue2
          href: https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Design-and-Modeling/06-mock-servers.md
          title: Learn More
          type: arrow-link
          rightIcon: arrow-right
    - description: >-
        Create API documentation in minutes. Combine OpenAPI documents with
        Markdown to create robust, searchable, internal and external
        [API documentation](/api-documentation-guide/basics/) for your organization.
      image: /images/docs/guides.svg
      shortName: Markdown Documentation
      title: Generate API Documentation with OpenAPI and Markdown
      ctas:
        - color: blue2
          href: https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Documentation/01-getting-started.md
          title: Learn More
          type: arrow-link
          rightIcon: arrow-right
    - description: >-
        Ask 100 API designers what makes a good API design and you'll get 101
        answers, but all most developers really want is consistency. Using an API
        style guide, can reduce decision making and improve consistency for all your teams.
        <br><br>
        With built-in linting and API style guides, powered by [Spectral](/spectral/), Stoplight
        Studio can improve the quality of your API. You can use the default style guide, extend it, or write one to match your organization's style guide (coming soon in Studio).
      image: /images/design/styleguides.svg
      shortName: Linting
      title: OpenAPI Linting and API Style Guides
      isReversed: true
      ctas:
        - color: blue2
          href: https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Design-and-Modeling/08-validation-style-guide.md
          title: Learn More
          type: arrow-link
          rightIcon: arrow-right
integrations:
  title: Collaborate Flexibly with Git Workflows
  shortTitle: Git Integration
  description: >-
    Collaborate on API designs easily using your existing Git repositories. Stoplight fits seamlessly into your current development workflows.
  images:
    - alt: Azure DevOps
      src: /images/integrations/azure.svg
    - alt: GitHub
      src: /images/integrations/github.svg
    - alt: GitLab
      src: /images/integrations/gitlab.svg
    - alt: Bitbucket
      src: /images/integrations/bitbucket.svg
actionBar:
  ctas:
    - color: blue2
      href: https://stoplight.io/welcome
      title: Get Started
      large: true
  enabled: true
  centered: true
  text: Ready to Start Designing Quality APIs?
  subtext: Available on Web and Desktop
solutionsNav:
  title: Explore the API Design Lifecycle
  icons:
    - icon: 'pencil'
      color: blue2
      title: Design
      href: /api-design
    - icon: code
      color: lavender
      title: Development
      href: /api-development
    - icon: chart-network
      color: blue
      title: Visibility
      href: /api-visibility
    - icon: server
      color: indigo
      title: Mocking
      href: /api-mocking/
    - icon: balance-scale
      color: purple
      title: Governance
      href: /api-governance
    - icon: book-open
      color: blue2
      title: Documentation
      href: /api-documentation
    - icon: user-friends
      color: yellow
      title: Collaboration
      href: /api-collaboration
meta:
  description: >-
    Create, collaborate, and prototype APIs with Stoplight Studio
  favicon: /images/mark_light_bg.png
  image: /images/home/thumbnail.png
  title: Stoplight Studio | OpenAPI Design, Planning & Modeling Tool
  robots: 'index, follow'
  twitter:
    description: >-
      Create, collaborate, and prototype APIs with Stoplight Studio
    image: /images/home/thumbnail.png
    title: Stoplight Studio | OpenAPI Design, Planning & Modeling Tool
    username: '@stoplightio'
  url: 'https://stoplight.io/studio'
