path: /studio
title: Stoplight Studio
relatedTags:
  - blog-design
hero:
  particles: true
  image:
    alt: Stoplight Studio
    src: /images/studio/hero.png
  subtitle: >-
    Create, collaborate, and prototype APIs with Stoplight Studio
  title: Effortless API Design
  ctas:
    - title: Get Quality
      href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-mac.dmg'
      color: green
      large: true
      rightIcon: ['fad', 'arrow-right']
    - title: Get Consistency
      href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-win.exe'
      color: purple
      large: true
      rightIcon: ['fad', 'arrow-right']
    - title: Get Visibility
      href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-linux-x86_64.AppImage'
      color: gold
      large: true
      rightIcon: ['fad', 'arrow-right']
featureSection:
  actionBar:
    ctas:
      - title: Get Quality
        href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-mac.dmg'
        color: green
        rightIcon: ['fad', 'arrow-right']
      - title: Get Consistency
        href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-win.exe'
        color: purple
        rightIcon: ['fad', 'arrow-right']
      - title: Get Visibility
        href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-linux-x86_64.AppImage'
        color: gold
        rightIcon: ['fad', 'arrow-right']
    enabled: true
    text: Ready to start designing APIs?
  title: Create API Designs in Minutes
  description: >-
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  features:
    - description: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /images/studio/studio-md.png
      shortName: Accelerate API Development
      title: Accelerate API Development

    - description: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /images/studio/todo.png
      overlayImage: true
      shortName: Avoid Redesigns
      title: Avoid Redesigns

    - description: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /images/studio/todo.png
      shortName: Maintain Team Coordination
      title: Maintain Team Coordination

meta:
  description: >-
    Create, collaborate, and prototype APIs with Stoplight Studio
  favicon: /images/mark_light_bg.png
  image: /images/studio/hero.png
  title: Stoplight Studio | OpenAPI Design, Planning & Modeling Tool
  robots: 'noindex, follow'
  twitter:
    description: >-
      Create, collaborate, and prototype APIs with Stoplight Studio
    image: /images/studio/hero.png
    title: Stoplight Studio | OpenAPI Design, Planning & Modeling Tool
    username: '@stoplightio'
