path: /studio
title: Stoplight Studio
color: blue
relatedTags:
  - blog-design
hero:
  particles: true
  image:
    alt: Stoplight Studio
    src: /images/studio/hero.png
  subtitle: >-
    Create, collaborate, and prototype APIs with Stoplight Studio
  title: Effortless API Design
  ctas:
    - title: Get Quality
      href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-mac.dmg'
      color: green
    - title: Get Consistency
      href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-win.exe'
      color: purple
    - title: Get Visibility
      href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-linux-x86_64.AppImage'
      color: gold
featureSection:
  actionBar:
    ctas:
      - title: Get Quality
        href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-mac.dmg'
        color: green
      - title: Get Consistency
        href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-win.exe'
        color: purple
      - title: Get Visibility
        href: 'https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-linux-x86_64.AppImage'
        color: gold
    enabled: true
    text: Ready to start designing APIs?
  title: Fluid Design
  description: >-
    With an intuitive interface, Stoplight Studio makes anyone designing an API specification more productive. 
    Spend less time learning how to use an API tool and more time actually architecting a robust API.
  features:
    - description: >-
        Enhance your design specification with clear formatting using Studio's integrated Markdown rendering. 
        Enable designers to easily construct familiar documentation for internal and external use that is both easy to create and easy to consume.
      image: /images/studio/hero.png
      shortName: Markdown Rendering
      title: Markdown Rendering

    - description: >-
        Aligning API stakeholders is not an easy task. But with a single accessible and detailed design 
        specification, teams will have the resources to provide insightful feedback while coordinating expectations.
      image: /images/studio/hero.png
      overlayImage: true
      shortName: Keep Stakeholders Coordinated
      title: Keep Stakeholders Coordinated

    - description: >-
        The OpenAPI documents designed by your team in Studio can be leveraged across the API lifecycle. 
        Use those same design files to unlock consistency, quality, and visibility through shared style guides, 
        instant mocking, and a powerful technical knowledge base.
      image: /images/studio/hero.png
      shortName: Unlock API Design with Stoplight
      title: Unlock API Design with Stoplight

meta:
  description: >-
    Create, collaborate, and prototype APIs with Stoplight Studio
  favicon: /images/mark_light_bg.png
  image: /images/studio/hero.png
  title: Stoplight Studio | OpenAPI Design, Planning & Modeling Tool
  robots: 'noindex, follow'
  twitter:
    description: >-
      Create, collaborate, and prototype APIs with Stoplight Studio
    image: /images/studio/hero.png
    title: Stoplight Studio | OpenAPI Design, Planning & Modeling Tool
    username: '@stoplightio'
