path: /careers/technical-customer-success-engineer
href: 'https://stoplight.careerplug.com/jobs/1035112/apps/new'
title: Technical Customer Success Engineer
tags:
  - careers
image: /images/job-app.jpeg
actionBar:
  ctas:
    - color: accent
      href: 'https://www.stoplight.com/about'
      title: About us
  enabled: true
  text: Find out more about what it's like to work at Stoplight
subtitle: >-
  FULL TIME, AUSTIN, TX
color: blue
hubspot:
  formId: b1cc69d9-4b4a-4ea4-a199-b9e7ed0b7a09
  portalId: '4892910'
leftContent:
  description: >-

    ### Stoplight is looking for a Customer Success Engineer (CSE) to join a fast growing Austin startup in the exciting domain of APIs and API Design Management. 

    The CSE position is a technical customer-facing role with a focus on helping customers achieve success in their use of the Stoplight product. You will work with customers by helping answer questions, solving problems, and ultimately being the voice of the customer within Stoplight.

    ### What is Stoplight?


    Stoplight helps organizations design, document, test, collaborate and 
    govern their APIs. We are the first product to effectively cover the entire 
    API development lifecycle.<br><br>Stoplight’s mission is to make any stakeholder 
    working with an API more productive. We work with individual developers to large companies 
    including EA, Spotify, Sendgrid, and many others.


    ### Why are we doing this?


    We created Stoplight because we found existing API solutions tools 
    to be inadequate. After talking with thousands of users and growing 
    to 500+ paying customers, it’s clear there is a massive void for 
    Stoplight to become the must-have workflow solution for any organization 
    looking to streamline their API strategy.


    ### What does it take to be successful in this role?


    - Answer questions, troubleshoot problems, and provide deep technical support for Stoplight customers across a wide array of topics.

    - Engage with customers and fellow Stoplight employees to solve critical, complex issues related to Stoplight products in a timely manner.

    - Deliver a great customer service experience with each customer interaction

    - Assist in writing, reviewing, and maintaining Stoplight product documentation

    - Participate in a working hours on-call rotation for urgent customer issues

    - Serve as the voice of the customer within Stoplight

    ### Requirements

    - Previous experience working directly with customers

    - Previous experience in Support, Systems Administration, Software Engineering, or other technical fields

    - Solid understanding of the modern web application stack. You are familiar with one or more of the following technologies: Typescript, React, GraphQL, REST, PostgreSQL, Kubernetes/Docker, nginx

    - Excellent communication skills, both written and verbal, with the ability to work and interact in a group or team

    - Strong problem-solving skills, with the ability to independently troubleshoot problems and identify workarounds

    - Self-motivated with a strong learning-orientation


    ### Benefits


    Competitive Salary. Stock Options. Full Medical, Dental, & Vision. 401k with 2% Company Match, Monthly Happy Hours, Quarterly Excursions.

    ### About 

    Headquartered in Austin, Texas, our team hails from across 
    the US and Europe, and is united by our passion for APIs. 
    From skeeball champions to rock climbers, tough mudders to 
    restaurateurs, each and every member brings their own unique 
    perspectives and experiences to the table. Thinking out of the 
    box is our purpose - the weirder the better - and challenging 
    the status quo is our culture.
meta:
  description: >-
    Stoplight is hiring a Technical Customer Success Engineer
  favicon:
  image:
  title: Technical Customer Success Engineer | Stoplight
  twitter:
    description: >-
      Stoplight is hiring a Technical Customer Success Engineer
    image: /images/gartner_cv_2019_rgb.png
    title: Technical Customer Success Engineer | Stoplight
    username: '@stoplightio'
