banners:
  - ends: 1609430400000
    markdown: >-
      Introducing Stoplight Platform, built from the ground up to work with your Git repos and workflows. <u
      class='ml-1'>**[Read the announcement](/blog/stoplight-platform)**</u>
    starts: 1570550400000
info:
  address:
    addressLocality: Austin
    addressRegion: TX
    alternateName: Stoplight
    description: >-
      Stoplight, providing engineering teams with the best way to document, test, and build web APIs.
    email: hello@stoplight.io
    name: Stoplight.io
    postalCode: '78741'
    streetAddress: 1834 E Oltorf St, Suite 200
  email: sales@stoplight.io
header:
  items:
    - links:
        - href: '/api-design/'
          icon: ['fad', 'pencil-paintbrush']
          title: Design
          titleColor: blue
        - href: '/api-development/'
          icon: ['fad', 'code']
          title: Development
          titleColor: orange
        - href: '/api-mocking/'
          icon: ['fad', 'database']
          title: Mocking
          titleColor: indigo
        - href: '/api-documentation/'
          icon: ['fad', 'book-open']
          title: Documentation
          titleColor: yellow
        - href: '/api-visibility/'
          icon: ['fad', 'chart-network']
          title: Visibility
          titleColor: green
        - href: '/api-governance/'
          icon: ['fad', 'balance-scale']
          title: Governance
          titleColor: purple
        - href: '/api-collaboration/'
          icon: ['fad', 'user-friends']
          title: Collaboration
          titleColor: yellow
      title: Use Cases
      width: 300
    - href: /pricing
      title: Pricing
    - href: /enterprise
      title: Enterprise
    - links:
        - href: 'https://meta.stoplight.io/docs/platform/'
          icon: ['fad', 'book-open']
          title: Docs
          titleColor: green
        - href: /blog
          icon: ['fad', 'blog']
          title: Blog
          titleColor: indigo
        - href: /video
          icon: ['fad', 'video']
          title: Videos
          titleColor: purple
        - href: /case-studies
          icon: ['fad', 'graduation-cap']
          title: Case Studies
          titleColor: indigo
        - divider: true
        - href: /api-types
          icon: ['fad', 'apple-crate']
          title: API Basics
          titleColor: lavender
        - href: /openapi
          title: What is OpenAPI?
          icon: ['fad', 'door-open']
          titleColor: blue2
        - href: /api-design-guide/basics
          icon: ['fad', 'paint-brush']
          title: API Design Guide
          titleColor: green
        - href: /mock-api-guide/basics
          icon: ['fad', 'database']
          title: API Mocking Guide
          titleColor: blue
        - href: /api-documentation-guide/basics
          icon: ['fad', 'bookmark']
          title: API Documentation Guide
          titleColor: purple
      title: Learn
      width: 300
    - aboutLinks:
        - href: '/about'
          icon: ['fad', 'robot']
          title: About Us
          titleColor: blue
        - href: '/blog'
          icon: ['fad', 'pencil']
          title: Blog
          titleColor: purple
        - href: 'https://support.stoplight.io'
          icon: ['fad', 'book-open']
          title: Help Center
          titleColor: indigo
        - href: /video
          icon: ['fad', 'video']
          title: Webinars
          titleColor: yellow
      title: About
      width: 300
    - href: 'https://stoplight.io/welcome/find'
      isButton: true
      title: Log in
      outlined: true
    - href: 'https://stoplight.io/welcome/create'
      isButton: true
      title: Get Started
      icon: 'arrow-right'
      colorOnPath: '/enterprise'
      bg: blue2

actionBar:
  ctas:
    - color: white
      href: /demo
      title: Book a Demo
      outlined: true
    - color: purple
      href: 'https://stoplight.io/welcome/create'
      title: Create a Free Account
  enabled: false
  text: Getting started is easy. Be up and running in minutes.
footer:
  columns:
    - links:
        - href: /studio
          title: Stoplight Studio
        - href: /open-source/spectral/
          title: Spectral
        - href: /open-source/prism/
          title: Prism
        - href: /enterprise
          title: Enterprise
      title: Products
    - links:
        - href: '/api-design/'
          title: Design
        - href: '/api-development/'
          title: Development
        - href: '/api-mocking/'
          title: Mocking
        - href: '/api-documentation/'
          title: Documentation
        - href: '/api-visibility/'
          title: Visibility
        - href: '/api-governance/'
          title: Governance
        - href: '/api-collaboration/'
          title: Collaboration
      title: Use Cases
    - links:
        - href: /blog
          title: Blog
        - href: /video
          title: Webinars
        - href: /case-studies
          title: Case Studies
        - href: /api-types
          title: API Types
        - href: /openapi
          title: What is OpenAPI?
      title: Learn
    - links:
        - href: /design
          title: API Design
        - href: /api-design-guide/basics
          title: API Design Guide
        - href: /documentation
          title: API Documentation
        - href: /api-documentation-guide/basics
          title: API Documentation Guide
        - href: /mocking/
          title: API Mocking
        - href: /mock-api-guide/basics
          title: API Mocking Guide
      title: Guides
    - links:
        - href: /about
          title: About Us
        - href: https://roadmap.stoplight.io/
          title: Roadmap
        - href: 'https://press.stoplight.io'
          title: Press
        - href: /contact-us
          title: Contact Us
        - href: 'https://support.stoplight.io'
          title: Help Center
      title: Company
  legal:
    - href: /privacy
      title: Privacy Policy
    - href: /terms
      title: Terms of Service
    - href: /policy
      title: Support Policy
  social:
    - href: 'https://twitter.com/stoplightio'
      icon: ['fab', 'twitter']
    - href: 'https://www.linkedin.com/company/stoplight'
      icon: ['fab', 'linkedin']
    - href: 'https://www.github.com/stoplightio'
      icon: ['fab', 'github']
meta:
  description: API Design Management for Teams and Enterprise | Stoplight
  favicon: /favicons/favicon.ico
  image: /images/home/thumbnail.png
  robots: 'index, follow'
  title: Stoplight
  twitter:
    description: API Design Management for Teams and Enterprise | Stoplight
    image: /images/home/thumbnail.png
    title: Stoplight
    username: '@stoplightio'
  url: 'https://stoplight.io'
  canonical: >-
    https://stoplight.io
customers:
  images:
    - alt: EA
      src: /images/ea.png
    - alt: Deutsche Bank
      src: /images/customers/Deutsche_Bank-Logo.svg
    - alt: Sendgrid
      src: /images/customers/SG_Twilio_Lockup_RGB.svg
    - alt: TiVo
      src: /images/tivo.png
    - alt: Zoom
      src: /images/zoom_logo.png
integrations:
  googleTagManager: GTM-58LWL5P
  hubspot: 4892910
  intercom: g7eo4oae
