banners:
  # - ends: 1609430400000
  #   markdown: >-
  #     Ready to accelerate your team's API Development by 36%? <u class='ml-1'>**[Request a Demo](https://stoplight.io/demo)**</u>
  #   starts: 1570550400000
  #   hideOnPath: ['/demo']
  # - ends: 1570550400000
  #   markdown: >-
  #     Learn API Design from Industry Experts! <u class='ml-1'>**[Register Now](https://zoom.us/webinar/register/5715699441732/WN_3xRpSTTOSoOpweidGLYVWQ)**</u> for the Studio Webinar on October 8th
  #   starts: 1569956400000
info:
  address:
    addressLocality: Austin
    addressRegion: TX
    alternateName: Stoplight
    description: >-
      Stoplight, providing engineering teams with the best way to document,
      test, and build web APIs.
    email: hello@stoplight.io
    name: Stoplight.io
    postalCode: '78741'
    streetAddress: 1834 E Oltorf St, Suite 200
  email: sales@stoplight.io
header:
  items:
    - links:
        - href: '/solutions/design'
          icon: ['fad', 'pencil-paintbrush']
          title: API Design
          titleColor: blue
        - href: '/solutions/development'
          icon: ['fad', 'code']
          title: API Development
          titleColor: orange
        - href: '/solutions/mocking'
          icon: ['fad', 'database']
          title: API Mocking
          titleColor: indigo
        - href: '/solutions/documentation'
          icon: ['fad', 'book-open']
          title: API Documentation
          titleColor: yellow
        - href: '/solutions/visibility'
          icon: ['fad', 'chart-network']
          title: API Visibility
          titleColor: red
        - href: '/solutions/governance'
          icon: ['fad', 'balance-scale']
          title: API Governance
          titleColor: purple
        - href: '/solutions/collaboration'
          icon: ['fad', 'user-friends']
          title: API Collaboration
          titleColor: yellow
        - divider: true
        - href: /case-studies
          icon: ['fad', 'graduation-cap']
          title: Case Studies
          titleColor: indigo
        - href: /api-design-guide/basics
          icon: ['fad', 'paint-brush']
          title: API Design Guide
          titleColor: green
        - href: /mock-api-guide/basics
          icon: ['fad', 'database']
          title: API Mocking Guide
          titleColor: blue
        - href: /api-documentation-guide/basics
          icon: ['fad', 'bookmark']
          title: API Documentation Guide
          titleColor: purple
      title: Solutions
      width: 300
    - aboutLinks:
        - href: '/about'
          icon: ['fad', 'robot']
          title: About Us
          titleColor: blue
        - href: '/blog'
          icon: ['fad', 'pencil']
          title: Blog
          titleColor: purple
        - href: 'https://support.stoplight.io'
          icon: ['fad', 'book-open']
          title: Help Center
          titleColor: indigo
        - href: 'https://community.stoplight.io/'
          icon: ['fad', 'users']
          title: Forum
          titleColor: green
        - href: /video
          icon: ['fad', 'video']
          title: Webinars
          titleColor: yellow
      title: About
      width: 300
    - href: /pricing
      title: Pricing
    - href: /enterprise
      title: Enterprise
    - href: /blog
      title: Blog
    - href: /about
      title: About
    - href: 'https://stoplight.io/welcome'
      altHref: 'https://stoplight.io/welcome'
      isButton: true
      title: Sign Up For Free
      altBg: blue2
      icon: ['fad', 'arrow-right']
actionBar:
  ctas:
    - color: white
      href: /demo
      title: Book a Demo
      outlined: true
    - color: purple
      href: 'https://stoplight.io/welcome'
      title: Create a Free Account
  enabled: false
  text: Getting started is easy. Be up and running in minutes.
footer:
  columns:
    - links:
        - href: /studio
          title: Stoplight Studio
        - href: /docs
          title: Stoplight Docs
        - href: /explorer
          title: Stoplight Explorer
        - href: /mocking
          title: Stoplight Mocking
        - href: /enterprise
          title: Enterprise
      title: Products
    - links:
        - href: '/solutions/design'
          title: API Design
        - href: '/solutions/development'
          title: API Development
        - href: '/solutions/mocking'
          title: API Mocking
        - href: '/solutions/documentation'
          title: API Documentation
        - href: '/solutions/visibility'
          title: API Visibility
        - href: '/solutions/governance'
          title: API Governance
        - href: '/solutions/collaboration'
          title: API Collaboration
      title: Solutions
    - links:
        - href: /open-source/spectral/
          title: Spectral
        - href: /open-source/prism/
          title: Prism
      title: Open Source
    - links:
        - href: /design
          title: API Design
        - href: /documentation
          title: API Documentation
        - href: /mocking
          title: API Mocking
      title: Use Cases
    - links:
        - href: 'https://support.stoplight.io'
          title: Help Center
        - href: /blog
          title: Blog
        - href: 'https://community.stoplight.io'
          title: Forum
        - href: /video
          title: Webinars
        - href: /case-studies
          title: Case Studies
        - href: /api-types
          title: API Types
        - href: /openapi
          title: What is OpenAPI?
      title: Resources
    - links:
        - href: /about
          title: About Us
        - href: https://stoplight.io/p/roadmap
          title: Roadmap
        - href: 'https://press.stoplight.io'
          title: Press
        - href: /contact-us
          title: Contact Us
      title: About
  legal:
    - href: /privacy
      title: Privacy
    - href: /terms
      title: Terms of Use
    - href: /policy
      title: Policy
  social:
    - href: 'https://twitter.com/stoplightio'
      icon: ['fab', 'twitter']
    - href: 'https://www.linkedin.com/company/stoplight'
      icon: ['fab', 'linkedin']
    - href: 'https://www.github.com/stoplightio'
      icon: ['fab', 'github']
meta:
  description: API Design Management for Teams and Enterprise | Stoplight
  favicon: /favicons/favicon.ico
  image: /images/home-hero.png
  robots: 'index, follow'
  title: Stoplight
  twitter:
    description: API Design Management for Teams and Enterprise | Stoplight
    image: /images/home-hero.png
    title: Stoplight
    username: '@stoplightio'
  url: 'https://stoplight.io'
customers:
  images:
    - alt: EA
      src: /images/ea.png
    - alt: Deutsche Bank
      src: /images/customers/Deutsche_Bank-Logo.svg
    - alt: Sendgrid
      src: /images/customers/SG_Twilio_Lockup_RGB.svg
    - alt: TiVo
      src: /images/tivo.png
    - alt: Zoom
      src: /images/zoom_logo.png
integrations:
  googleTagManager: GTM-58LWL5P
  hubspot: 4892910
  intercom: g7eo4oae
